
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package RegexParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CARET = 23;
  public static final int PLUS = 20;
  public static final int RPAREN = 28;
  public static final int METAVERTICALTAB = 12;
  public static final int METANOTWORD = 14;
  public static final int DOLLAR = 24;
  public static final int DIGIT = 16;
  public static final int NOTDIGIT = 17;
  public static final int STAR = 21;
  public static final int METARETURN = 4;
  public static final int RCURLY = 30;
  public static final int METANOTBOUNDARY = 7;
  public static final int METANOTDIGIT = 9;
  public static final int LPAREN = 27;
  public static final int LBRACKET = 25;
  public static final int METANEWLINE = 3;
  public static final int METAWORD = 13;
  public static final int RBRACKET = 26;
  public static final int LCURLY = 29;
  public static final int COMMA = 32;
  public static final int METABOUNDARY = 6;
  public static final int METADIGIT = 8;
  public static final int METATAB = 2;
  public static final int EOF = 0;
  public static final int METANOTSPACE = 11;
  public static final int UNION = 31;
  public static final int MINUS = 18;
  public static final int DOT = 19;
  public static final int error = 1;
  public static final int METASPACE = 10;
  public static final int METAFEED = 5;
  public static final int OPTIONAL = 22;
  public static final int ESCAPEDCHAR = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "METATAB",
  "METANEWLINE",
  "METARETURN",
  "METAFEED",
  "METABOUNDARY",
  "METANOTBOUNDARY",
  "METADIGIT",
  "METANOTDIGIT",
  "METASPACE",
  "METANOTSPACE",
  "METAVERTICALTAB",
  "METAWORD",
  "METANOTWORD",
  "ESCAPEDCHAR",
  "DIGIT",
  "NOTDIGIT",
  "MINUS",
  "DOT",
  "PLUS",
  "STAR",
  "OPTIONAL",
  "CARET",
  "DOLLAR",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "UNION",
  "COMMA"
  };
}

