
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 13;
  public static final int RPAREN = 21;
  public static final int OR = 14;
  public static final int IMPLICATION = 11;
  public static final int TRUE = 2;
  public static final int EVENTUALLY = 18;
  public static final int LPAREN = 20;
  public static final int ID = 4;
  public static final int EXP = 5;
  public static final int WEAKUNTIL = 7;
  public static final int RELEASE = 9;
  public static final int EOF = 0;
  public static final int ALWAYS = 17;
  public static final int DUAL = 8;
  public static final int FALSE = 3;
  public static final int error = 1;
  public static final int UNTIL = 6;
  public static final int NEGATION = 19;
  public static final int XOR = 15;
  public static final int NEXT = 16;
  public static final int STRONGRELEASE = 10;
  public static final int EQUIVALENCE = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TRUE",
  "FALSE",
  "ID",
  "EXP",
  "UNTIL",
  "WEAKUNTIL",
  "DUAL",
  "RELEASE",
  "STRONGRELEASE",
  "IMPLICATION",
  "EQUIVALENCE",
  "AND",
  "OR",
  "XOR",
  "NEXT",
  "ALWAYS",
  "EVENTUALLY",
  "NEGATION",
  "LPAREN",
  "RPAREN"
  };
}

