%3f\s+url=[^\n\r]*httpUser-Agent\x3A
A-311[^\n\r]*Attached\sHost\x3AWordmyway\.comhoroscope2
AD\s+c\.goclick\.com\w+asdbiz\x2Ebizfrom\x7croogoo\x7cCurrent
AdTools\sdownloadfile\x2eorg\w+com\x3E[^\n\r]*as\x2Estarware\x2EcomOS\x2FSSKCstech\x2Eweb-nexus\x2Enet
Agent.*as\x2Estarware\x2Ecom\s+ServerToolbarcojud\x2Edmcast\x2Ecom
AgentHWAEUser-Agent\x3A
Apofis.*Port\x2E\s+\x2FNFO\x2CRegistered
CUSTOM\swww\x2Elocators\x2Ecom\d+Seconds\-
ChildWebGuardian\d+Subject\x3A
CommonName.*st=\s+Contactfrom=GhostVoiceServerUser-Agent\x3A
Contact\d+Host\x3A[^\n\r]*User-Agent\x3AHost\x3aMailHost\x3aMSNLOGOVN
Cookie\x3a.*Host\x3A.*ldap\x3A\x2F\x2F
Current[^\n\r]*server[^\n\r]*Host\x3Aocllceclbhs\x2fgth
Days\s+HWAE\s+Host\x3APortawww\.thecommunicator\.net
Desktop.*Hello\x2E.*Referer\x3AToolbar
DigExt.*\x23\x23\x23\x23
EFError.*Host\x3A\swww\x2emalware-stopper\x2ecom
EFError.*\x2Fcs\x2Fpop4\x2F[^\n\r]*
Everyware.*Email.*Host\x3Astepwww\x2Ekornputers\x2Ecom
EvilFTP\s+%3f[^\n\r]*\.bmpfilename\x3D\x22
FTP.*www\x2Ewordiq\x2Ecom
Fictional[^\n\r]*v\x3B[^\n\r]*\x22Stealth\d+moreKontikiHost\x3aAcmeEvilFTPHost\x3ATOOLBARSupremePort\x2E
FreeAccessBar\s+hostie[^\n\r]*CodeguruBrowser\dStableWeb-MailUser-Agent\x3A195\.225\.Subject\x3A
From\x3A.*Host\x3A\s+Downloadfowclxccdxn\x2fuxwn\.ddy
From\x3A\w+SoftActivity\d+
GmbH\d+Host\x3A\w+adblock\x2Elinkz\x2EcomUser-Agent\x3Aemail
Guarded\s+ready\w+PARSERHost\x3aA-311ServerUser-Agent\x3Ascn\x2emystoretoolbar\x2ecom
HBand,\sHost\x3A[^\n\r]*lnzzlnbk\x2fpkrm\.fin
HWAE[^\n\r]*Email[^\n\r]*User-Agent\x3AUser-Agent\x3awowokayHost\x3A
HWPE[^\n\r]*Basic.*LOGsearches\x2Eworldtostart\x2Ecom
Host\x3A.*Host\x3A\s+www\x2Eyoogee\x2Ecom
Host\x3A.*NETObserve\d+Host\x3aohgdhkzfhdzo\x2fuwpOK\r\n
Host\x3A.*Peer.*Host\x3ABasicurl=http\x3A
Host\x3A.*c=[^\n\r]*KeyloggerHost\x3Awww\.trackhits\.cc
Host\x3A.*client\x2Ebaigoo\x2Ecom
Host\x3A.*rt[^\n\r]*Host\x3AUser-Agent\x3A
Host\x3A.*www\x2e2-seek\x2ecom\x2fsearch
Host\x3A[^\n\r]*Travel[^\n\r]*From\x3Awww\x2EZSearchResults\x2Ecom
Host\x3A[^\n\r]*\x2Fbar_pl\x2Fshdoclc\.fcgi
Host\x3A[^\n\r]*adblock\x2Elinkz\x2Ecom[^\n\r]*HTTPfromtoADWindowsstep
Host\x3A[^\n\r]*cache\x2Eeverer\x2Ecom\s+from\.myway\.comToolbar
Host\x3A\d+Black\s+daosearch\x2EcomMyPostwww\.raxsearch\.com
Host\x3A\d+Host\x3A.*communitytipHost\x3AGirafaClient
Host\x3A\d+Subject\x3A[^\n\r]*Seconds\-ovplHost\x3AHost\x3ADownload
Host\x3A\d+UI2.*areprotocolhttp\x3A\x2F\x2Fwww\.searchinweb\.com\x2Fsearch\.php\?said=bar
Host\x3A\d+rprpgbnrppb\x2fci[^\n\r]*RXFilteredDmInf\x5E
Host\x3A\dKeylogger.*Onetrustyfiles\x2Ecom
Host\x3A\dMicrosoft\w+\+Version\+
Host\x3A\dName=Your\+Host\+is\x3A.*has\s+ComputerKeylogger\x2EcomHost\x3A
Host\x3A\dtoolbar\x2Ehotblox\x2Ecom\dHost\x3Ahttp\x3A\x2F\x2Fmysearch\.dropspam\.com\x2Findex\.php\?tpid=
Host\x3A\s+Boss\s+media\x2Etop-banners\x2Ecom
Host\x3A\s+Host\s+Host\x3aInformationX-OSSproxy\x3aas\x2Estarware\x2Ecom
Host\x3A\s+\.ico.*SpyAgentHost\x3A
Host\x3A\s+\x2Ftoolbar\x2Fico\x2F\dencoderserverreport\<\x2Ftitle\>
Host\x3A\s+ulmxct\x2fmqoyc\s+securityOmFkbWluADROARad\x2Emokead\x2Ecom
Host\x3A\sHello\x2E.*forum=
Host\x3A\w+User-Agent\x3A\sTeomaBarHost\x3AHoursHost\x3AHost\x3A
Host\x3A\w+www.*ToolbartheServer\x3Awww\x2Esearchreslt\x2Ecom
Host\x3a.*\x2Frss.*Desktopcargo=report\<\x2Ftitle\>
Host\x3a.*ver\dRobert\dDmInf\x5EinfoSimpsonUser-Agent\x3AClientwww\x2Einternet-optimizer\x2Ecom
Host\x3a[^\n\r]*A-311\s+lnzzlnbk\x2fpkrm\.finSubject\x3aBasic
Host\x3a[^\n\r]*pgwtjgxwthx\x2fbyb\.xky[^\n\r]*source%3Dultrasearch136%26campaign%3Dsnap
Host\x3a[^\n\r]*snprtz\x7Cdialno\s+Agent\s+Host\x3AUser-Agent\x3A\.cfgUser-Agent\x3Axbqyosoe\x2fcpvm
Host\x3a\dATTENTION\x3A[^\n\r]*From\x3AUser-Agent\x3A
Host\x3a\s+is\s+User-Agent\x3Acid=tb\x2eCookie\x3A
Host\x3a\w+Host\x3A.*Host\x3aToolbarServerserver\x7D\x7BSysuptime\x3A
Host\x3a\w+Host\x3A[^\n\r]*Host\x3AHost\x3a\x5Chome\/lordofsearch
Host\x3a\w+Pre.*Keyloggeradfsgecoiwnfhirmvtg\x2fggqh\.kqh
IDENTIFY.*\/cgi-bin\/PopupV.*Host\x3Asearchreslt
IDENTIFY.*\x2Fezsb\d+X-Mailer\x3A
IP-[^\n\r]*URL\d\x7croogoo\x7c\.cfgmPOPrtCUSTOMPalToolbar
IP.*encoder\d+SAHPORT-User-Agent\x3A
Information.*Firewall\s+ised2k\xc0STATUS\xc0Server
Keylogger[^\n\r]*dll\x3F\w+www2\x2einstantbuzz\x2ecom\s+Online100013Agentsvr\x5E\x5EMerlinHost\x3AHost\x3Aport
Keystrokes.*LOG.*Host\x3Awww\x2Eserverlogic3\x2Ecom
Log[^\n\r]*Host\x3A\dHOST\x3AUser-Agent\x3A
Logger.*Host\x3A.*\x2Fcommunicatortb\x7croogoo\x7c
Logger.*aresflashdownloader\x2Ecom
Logger\w+searchreslt\dSubject\x3AHANDY\x2FrssScaner
Login.*Host\x3A\s+Host\x3AHost\x3Aalertseqepagqfphv\x2fsfd
Login\sHost\x3A\w+Host\x3aiz=iMeshBar%3f\x2Fbar_pl\x2Fchk_bar\.fcgi
Logs.*with\x3A\s+OnlineServer\x3aYeah\!
Mirar_KeywordContent
NSIS_DOWNLOAD.*User-Agent\x3A\s+gpstool\x2eglobaladserver\x2ecom
NetTracker.*Theef2[^\n\r]*versionA-311Subject\x3awww\x2Epcsentinelsoftware\x2Ecom
Online\x2521\x2521\x2521\sUser-Agent\x3A\d+HXDownloadasdbiz\x2Ebiz
PASSW=.*www\x2Emakemesearch\x2Ecom.*HBand,X-Mailer\x3A
PASSW=\s+\x2Fta\x2FNEWS\x2F.*loomcompany\x2Ecom
PORT\x3D\s+User-Agent\x3A\s+ProAgentUI2Host\x3A00000www\x2Ezhongsou\x2Ecom
Peer\s+CodeguruBrowser.*UNSEEN\x22Host\x3Ahirmvtg\x2fggqh\.kqh
Points\d+Host\x3a\stoBasicwww\x2Ewebcruiser\x2Ecc
Port.*Pro.*www\x2eproventactics\x2ecomwv=update\.cgidrivesDays
Port\x2E[^\n\r]*007\d+Logsdl\x2Eweb-nexus\x2Enet
PromulGate\s+SbAts.*Uservclxatmlhavj\x2fvsywww\x2Evip-se\x2Ecom
Ready[^\n\r]*User-Agent\x3A\s+Client\dFrom\x3AWebtool\x2Eworld2\x2EcnUser-Agent\x3AUser-Agent\x3a
Ready\s+Eye.*http\x3A\x2F\x2Fsupremetoolbar
Referer\x3A.*User-Agent\x3A
Referer\x3A.*notification.*qisezhin\x2fiqor\.ymspasServer\x3a
Referer\x3ATencentTraveler
Referer\x3A\s+HXDownload.*Referer\x3AGREATDripline
Referer\x3A\s+www\x2eproventactics\x2ecom
Reporter\s+Host\x3A.*search\x2econduit\x2ecomTM_SEARCH3
Reports[^\n\r]*User-Agent\x3A.*largePass-Onseqepagqfphv\x2fsfd
Runner.*\x2Ehtml[^\n\r]*NetControl\x2EServer\d+media\x2Edxcdirect\x2Ecom\.smx\?PASSW=SAH
SbAts[^\n\r]*Subject\x3a\d+dcww\x2Edmcast\x2Ecom
SecureNet.*\x2Fsearchfast\x2F
Server.*Host\x3a.*SpyAgentRootHost\x3A
Server\s+www\x2Epeer2mail\x2Ecom.*Subject\x3AReferer\x3A
ShadowNet\dsearchreslt\sTROJAN-Host\x3AYWRtaW46cGFzc3dvcmQ
SoftActivity\s+User-Agent\x3A.*LogsHost\x3AHost\x3AX-Mailer\x3a
Software\s+User-Agent\x3A.*FictionalUser-Agent\x3AUser-Agent\x3a
SpyAgent\d+nick_name=CIA-Test\d+url=http\x3A\d+\x2FNFO\x2CRegistered\x28BDLL\x29
SpyAgent\d+sErver\s+User-Agent\x3A
Spy\s+\x0d\x0a.*YAHOOdestroyed\x21Host\x3a
Spynova\s+ZC-Bridge.*Host\x3A\s+TPSystemHost\x3AHost\x3ashow\x2Eroogoo\x2EcomX-Mailer\x3A
SpywareStrike.*Subject\x3A\s+Pcast\x2Edat\x2EToolbar
Spyware\s+ToolBar\s+User-Agent\x3AMM_RECO\x2EEXEToClientonAlert
Strip-Player.*MyAgent.*\x2Fnewsurfer4\x2F
Subject\x3A[^\n\r]*Arrow[^\n\r]*whenu\x2Ecom
Subject\x3A\s+Host\x3A.*www\x2Ealfacleaner\x2Ecom
Subject\x3A\swww\x2Esearchwords\x2Ecom
Supervisor\s+User-Agent\x3A
Supreme\d+Host\x3A\d+yxegtd\x2fefcwgHost\x3ATPSystem
TOOLBAR\s+dist\x2Eatlas\x2Dia\x2Ecom
This\s+\x7D\x7BPassword\x3A\d+
Toolbar.*www\x2Ewebcruiser\x2Ecc\w+www\x2Etopadwarereviews\x2Ecom
Toolbar[^\n\r]*User-Agent\x3A\w+Host\x3A.*toX-Mailer\x3aLogsmax-Cookie\x3aAppName
Toolbar[^\n\r]*tvshowtickets\w+weatherHost\x3AUser-Agent\x3Atwfofrfzlugq\x2feve\.qd
Toolbar[^\n\r]*url=\d+Host\x3AWelcome\x2FcommunicatortbGateCrasher
Travel.*www\x2Etopadwarereviews\x2Ecom\s+v2\x2E0www\.raxsearch\.com
URLBlaze.*User-Agent\x3A.*mPOPUser-Agent\x3A
User-Agent\x3A.*Host\x3A.*w3whowww\x2Esogou\x2Ecom
User-Agent\x3A.*Host\x3A\dName=Your\+Host\+is\x3A
User-Agent\x3A.*Host\x3a\s+www\x2Ewordiq\x2Ecom\s+Subject\x3AAlexaOnline\x2521\x2521\x2521
User-Agent\x3A.*OSSProxy
User-Agent\x3AFrom\x3Awww\x2Eonlinecasinoextra\x2EcomHost\x3A
User-Agent\x3A[^\n\r]*HTTP_RAT_
User-Agent\x3A[^\n\r]*Host\x3A.*\x2Ftoolbar\x2FHost\x3AUser-Agent\x3A
User-Agent\x3A[^\n\r]*aadserver\dYOUR\x2Fxml\x2Ftoolbar\x2F
User-Agent\x3A[^\n\r]*connection
User-Agent\x3A[^\n\r]*quick\x2Eqsrch\x2Ecom.*www\.searchinweb\.com
User-Agent\x3A\d+Desktop\sIDENTIFY666User-Agent\x3A\x5BStatic
User-Agent\x3A\d+Theef2\sHost\x3A
User-Agent\x3A\d+dll\x3F.*started\x2EfeedbackUser-Agent\x3A
User-Agent\x3A\d+wjpropqmlpohj\x2flo\s+media\x2Edxcdirect\x2Ecom
User-Agent\x3A\s+Host\x3A[^\n\r]*Hourspjpoptwql\x2frlnjFrom\x3Asbver\x3aGhost
User-Agent\x3A\s+\x2APORT3\x2A\d+
User-Agent\x3A\s+information\swww\x2Etopadwarereviews\x2Ecom
User-Agent\x3A\s+www\x2Emyarmory\x2Ecom
User-Agent\x3a.*%3f\s+Subject\x3Aas\x2Estarware\x2Ecom
User-Agent\x3a[^\n\r]*Echelon.*Blacksnprtz\x7CdialnoSearch
User-Agent\x3a\s+Host\x3A\s+proxystylesheet=Excitefhfksjzsfu\x2fahm\.uqs
User-Agent\x3a\s+sErver\s+-~-GREATHost\x3a
User-Agent\x3a\s+www\x2Einternet-optimizer\x2Ecom
User-Agent\x3a\w+Owner\x3A
User.*User-Agent\x3A.*ResultATTENTION\x3Ariggiymd\x2fwdhi\.vhi
Web-Mail\s+\x2Fcgi\x2Flogurl\.cgi.*SurveillanceHost\x3a
Word\w+My\s+\x22TheZC-BridgeUser-Agent\x3AserverUSER-Attached
X-Mailer\x3a.*User-Agent\x3A[^\n\r]*ulmxct\x2fmqoyc
X-Mailer\x3a[^\n\r]*Host\x3A\s+cyber@yahoo\x2Ecom
X-Mailer\x3awlpgskmv\x2flwzo\.qv#Subject\x3aActivity
XP\d+Acme\s+\x2Fcbn\x2Fnode=Host\x3A\x3Fsearch\x3DversionContact
Xtra\s+Host\x3A\s+Referer\x3aThisSubject\x3a
YAHOO.*Host\x3A.*\x2Fcs\x2Fpop4\x2F
YWRtaW46cGFzc3dvcmQ[^\n\r]*DA[^\n\r]*Host\x3Awww\x2Ee-finder\x2Ecc
\.bmp[^\n\r]*couponbar\.coupons\.com.*Host\x3AHost\x3aHTTPwww
\.cfg.*spyblini\x2Eini[^\n\r]*urfiqileuq\x2ftjzu.*Host\x3A666password\x3B1\x3BOptixGmbHPG=SPEEDBARcuReferer\x3A
\.fcgi[^\n\r]*Host\x3A\s\x5D\x2520\x5BPort_NETObserveTM_SEARCH3
\/cgi-bin\/PopupV\s+insert.*Host\x3aHELOHourssurvey\.asp\?nUserId=
\[DRIVE\w+updates[^\n\r]*\x22StarLogger\x22User-Agent\x3AJMailUser-Agent\x3A
\stoolbar\.anwb\.nl.*Host\x3A
\stoolbar\.anwb\.nl\s+A-311.*Host\x3aHost\x3Ayddznydqir\x2fevi
\swww\.fast-finder\.com[^\n\r]*\x2Fbar_pl\x2Fchk\.fcgi\d+Toolbar
\x22The\s+e2give\.com\s+NETObserve
\x22reaction\x2Etxt\x22.*Cookie\x3a[^\n\r]*richfind\x2EcomSimpsonFrom\x3A
\x28BDLL\x29\s+CD\x2F.*Host\x3A
\x28\x29\s+WatchDog\sNetspy\d+pjpoptwql\x2frlnjX-Mailer\x3aHost\x3asnprtz\x7Cdialnoref\x3D\x25user\x5Fid
\x28robert\x40blackcastlesoft\x2Ecom\x29
\x2APORT3\x2A\s+Warez.*X-Mailer\x3ASubject\x3AKEY=
\x2Ehtml.*cm.*www\x2Epeer2mail\x2EcomConnectedStubbyawbeta\.net-nucleus\.com
\x2Fcgi\x2Flogurl\.cgi.*User-Agent\x3A.*Host\x3Awww\x2EZSearchResults\x2Ecom
\x2Fcgi\x2Flogurl\.cgi\s+IDENTIFY.*max-www\x2Eu88\x2Ecn
\x2Fcommunicatortb[^\n\r]*\x2FGR.*Reportinfowhenu\x2Ecom
\x2Fcs\x2Fpop4\x2F\s+data\.warezclient\.com
\x2Fezsb\s+hirmvtg\x2fggqh\.kqh\dRemotetoolsbar\x2Ekuaiso\x2Ecom
\x2Frss\d+answer\sHost\x3A
\x2Ftoolbar\x2Fsupremetb\s+wjpropqmlpohj\x2flo\s+resultsmaster\x2Ecom
\x7D\x7BTrojan\x3A\w+Host\x3A\s\d\x2El
\x7D\x7BTrojan\x3A\w+by\d+to\w+dddlogin\x2Edudu\x2EcomSurveillanceIPOblivion
ad\x2Esearchsquire\x2Ecom[^\n\r]*User-Agent\x3A
alert\d+an.*Spyiz=e2give\.comrichfind\x2Ecom
aohobygi\x2fzwiw\s+\+The\+password\+is\x3A
are\d+Version\d+JMailBoxHostGENERAL_PARAM2
are\d+X-Mailer\x3a+\d+v=User-Agent\x3a
are\s+Toolbar\s+X-Mailer\x3AInformationsearchnuggetspastb\x2Efreeprod\x2Ecom
as\x2Estarware\x2Ecom.*Casino.*LOG.*FilteredHost\x3Ae2give\.com\x2Fnewsurfer4\x2F
as\x2Estarware\x2Ecom\x2Fdp\x2Fsearch\?x=.*X-Mailer\x3A
c\.goclick\.com[^\n\r]*is\s+URLBlaze
cdpView.*protocol.*\x2Fs\x28robert\x40blackcastlesoft\x2Ecom\x29
clvompycem\x2fcen\.vcn.*Host\x3A\s+toolbar_domain_redirectHost\x3a
cojud\x2Edmcast\x2Ecom\sApofis\w+Referer\x3Awww\x2Emirarsearch\x2Ecom
com.*is[^\n\r]*Host\x3A\s+User-Agent\x3Au=serverFILE\x2Fxml\x2Ftoolbar\x2Fcheck=at\x3aHost\x3A
com\dsearch\x2econduit\x2ecom\s+User-Agent\x3A
com\x2Findex\.php\?tpid=.*pop\x2Epopuptoast\x2Ecom.*Host\x3A
configINTERNAL\.ini.*SecureNet\s+User-Agent\x3Aregister\.asp
corep\x2Edmcast\x2Ecom[^\n\r]*Referer\x3a.*is[^\n\r]*KeyloggerExplorerfileserverSI\|Server\|www\x2Emyarmory\x2Ecom
couponbar\.coupons\.com\dOwner\x3A\s+Host\x3A
devSoft\x27s\s+Host\x3A\s+Host\x3A
e2give\.com.*Host\x3A.*Host\x3a
e2give\.com.*Redirector\x22.*Host\x3A
encoder[^\n\r]*\.cfg\s+Host\x3AWeHost\x3a
filename=\x22\dDA\s+www\x2Epeer2mail\x2Ecom
for.*www\x2Eeblocs\x2Ecom\d\x2Fiis2ebs\.asp\d\<title\>Actual\x2Fpagead\x2Fads\?search2\.ad\.shopnav\.com\x2F9899\x2Fsearch\x2Fresults\.php
for[^\n\r]*Host\x3A\sinternalcyber@yahoo\x2EcomHeadersRedirection
forum=.*Explorer\s+Host\x3Aact=Host\x3aUser-Agent\x3A
frame_ver2\s+www\x2eurlblaze\x2enet\s+source\=IncrediFind\s+AgentHost\x3AHost\x3AHost\x3A\x2FGRSpynova3AFrom\x3A
from\s+\x2Fdss\x2Fcc\.2_0_0\.[^\n\r]*uploadServer
function.*WEBCAM-.*User-Agent\x3a
gdvsotuqwsg\x2fdxt\.hdFrom\x3ahirmvtg\x2fggqh\.kqh
gpstool\x2eglobaladserver\x2ecom\daction\x2E\w+data2\.activshopper\.com
hjhgquqssq\x2fpjm[^\n\r]*User-Agent\x3A
hostie\s+freeIPaddrs\s+TPSystemHost\x3a\x7D\x7BUser\x3AAlert\x2Fcgi-bin\x2F
http\s+Host\x3A[^\n\r]*WinInet3Azopabora\x2Einfo\x2Fnotifier\x2FUser-Agent\x3A
http\x3A\x2F\x2Ftv\x2Eseekmo\x2Ecom\x2Fshowme\x2Easpx\x3Fkeyword=
httphost[^\n\r]*www\x2Emaxifiles\x2Ecom
jsp\s+pjpoptwql\x2frlnj[^\n\r]*Host\x3A
kl\x2Esearch\x2Eneed2find\x2Ecom\ssource%3Dultrasearch136%26campaign%3Dsnap
logs\d+X-Mailer\x3a\d+url=enews\x2Eearthlink\x2Enet
logs\s+TCP.*Toolbarads\.grokads\.com
messages.*Windows.*From\x3AX-Mailer\x3a+\x2Fcbn\x2FearchSchwindler
name\x2ecnnic\x2ecn\scom\x2Findex\.php\?tpid=\s\x5BStatic.*\x2Fbar_pl\x2Fb\.fcgi
news\s+Host\x3A.*Peerwww\x2Elocators\x2Ecom
offers\x2Ebullseye-network\x2Ecom[^\n\r]*this\dwww\x2Etrustedsearch\x2Ecom
offers\x2Ebullseye-network\x2Ecom\s+news[^\n\r]*WatcherUser-Agent\x3A
ovpl\s+\x7D\x7BPort\x3A.*SOAPAction\x3A.*adfsgecoiwnfHost\x3A\x3Fsearch\x3D
phpinfo[^\n\r]*195\.225\.\dccecaedbebfcaf\x2Ecom
pjpoptwql\x2frlnj\d+waiting\d+ocllceclbhs\x2fgth\w+gdvsotuqwsg\x2fdxt\.hd^User-Agent\x3A
ppcdomain\x2Eco\x2Euk.*Spy\-Locked\s+Exploiter\w+\x2Fr\x2Fkeys\x2FkeysS\x3aUsers\x5cIterenet
protocol\s+3A\s+data2\.activshopper\.comUser-Agent\x3A
quick\x2Eqsrch\x2Ecom\s+Apofis\d+ToolBar
quick\x2Eqsrch\x2Ecom\s+WinSession\s+Server\x00
requested.*zmnjgmomgbdz\x2fzzmw\.gzt\s+Reportsdaosearch\x2Ecom
s_sq=aolsnssignin.*LOG\s+Host\x3ASubject\x3Aonline-casino-searcher\.com
search2\.ad\.shopnav\.com\x2F9899\x2Fsearch\x2Fresults\.php.*Logger.*Subject\x3a\s+Host\x3AHost\x3A
search\.dropspam\.com.*SupportFiles.*Referer\x3A
search\.dropspam\.com.*pjpoptwql\x2frlnj
search\x2econduit\x2ecom\sPARSER.*
searchnugget.*Referer\x3A\s+User-Agent\x3AHost\x3A
select\x2FGet\s+Host\x3A.*ppcdomain\x2Eco\x2Euk
server\s+www\x2Eyok\x2Ecom\s+Host\x3A
smrtshpr-cs-.*TPSystem\s+dist\x2Eatlas\x2Dia\x2Ecom
software.*com\x2Findex\.php\?tpid=\s+Host\x3A\x2Ftoolbar\x2Fsupremetb
spyblpat.*is[^\n\r]*BarFrom\x3AHost\x3Agdvsotuqwsg\x2fdxt\.hdPASSW=
sql.*badurl\x2Egrandstreetinteractive\x2Ecom
st=\s+Stopper\s+Host\x3AAgentProjectMyWebSearchSearchAssistant
st=\s+www\.iggsey\.com.*BackAtTaCkadserver\.warezclient\.com
subject\x3A.*Login\s+adfsgecoiwnf
t=[^\n\r]*Host\x3A\s+Basicaohobygi\x2fzwiw
that.*CodeguruBrowser.*CasinoBladeisInsideupdate\.cgiHost\x3A
this\s+MyBrowser\d+Redirector\x22ServerHost\x3AX-Mailer\x3A
this\w+c\.goclick\.com\d
too[^\n\r]*User-Agent\x3A\sHost\x3A.*IP-WindowsAttachedPalas\x2Estarware\x2Ecom\x2Fdp\x2Fsearch\?x=
toolbar\.wishbone\.com\s+GET.*toowww\.123mania\.com\x2EphpLibrary
toolbarplace\x2Ecom.*Host\x3A\dgpstool\x2eglobaladserver\x2ecom
toolbarplace\x2Ecom[^\n\r]*Server[^\n\r]*X-Mailer\x3a\sUser-Agent\x3aHost\x3ABar\x2Fnewsurfer4\x2F
toolsbar\x2Ekuaiso\x2Ecom\d\x2Fbar_pl\x2Fchk_bar\.fcgi
track\s+community\d+4\x2e8\x2e4www\x2Emaxifiles\x2Ecom
traffbest\x2Ebiz\d+\.compress.*sidebar\.activeshopper\.comaresflashdownloader\x2Ecom
trustyfiles\x2Ecom\d+lnzzlnbk\x2fpkrm\.fin\s+
tv\x2E180solutions\x2Ecom\s+have\s+Dayspassword\x3B0\x3BIncorrect
upgrade\x2Eqsrch\x2Einfo.*report.*Host\x3A.*Host\x3Akwd-i%3fUser-Agent\x3Awww\x2eproventactics\x2ecom
upgrade\x2Eqsrch\x2Einfo[^\n\r]*dcww\x2Edmcast\x2Ecom
url=\swww\x2Ealfacleaner\x2Ecom\d+Host\x3A\x2Fproducts\x2Fspyblocs\x2F
url=http\x3A\s+jsp[^\n\r]*serverHOST\x3ASubject\x3Ai\-femdom\x2Ecom
uuid=\s+User-Agent\x3a\d+\x5Chome\/lordofsearch
ver\d+sports\w+whenu\x2Ecomwp-includes\x2Ffeed\x2Ephp\x3F
version.*Host\x3a\s+iWonHost\x3apjpoptwql\x2frlnj
whenu\x2Ecom\d+Agent\stoWebupdate\.cgithisHost\x3aconnection
wowokay\d+FTP\s+Host\x3AFiltered\x22reaction\x2Etxt\x22
wp-includes\x2Ftheme\x2Ephp\x3F.*Apofis\s+TencentTraveler
www.*tool\x2Eworld2\x2Ecn
www\.actualnames\.com.*www\.klikvipsearch\.com.*\x3C\x2Fchat\x3E
www\.iggsey\.com\sX-Mailer\x3a[^\n\r]*on\x3Acom\x3E2\x2E41Client
www\.thecommunicator\.net[^\n\r]*iufilfwulmfi\x2friuf\.lio
www\x2EZSearchResults\x2Ecom\dBar.*sponsor2\.ucmore\.com
www\x2Ealtnet\x2Ecom[^\n\r]*Host\x3A
www\x2Ecameup\x2Ecom\s+spyblini\x2Eini
www\x2Eemp3finder\x2Ecom\d+ZOMBIES\x5fHTTP\x5fGET
www\x2Eezula\x2Ecom.*FTP.*User-Agent\x3Acontainsw3whoreport
www\x2Eezula\x2Ecom.*com[^\n\r]*SpyBuddy
www\x2Efreescratchandwin\x2Ecom\d+Server.*www\x2Ecameup\x2Ecom
www\x2Efreescratchandwin\x2Ecom\w+Port.*User-Agent\x3AToolbarkit
www\x2Emaxifiles\x2Ecom.*Host\x3A
www\x2Epurityscan\x2Ecom.*
www\x2Ericercadoppia\x2Ecom[^\n\r]*xml\s+User-Agent\x3A
www\x2Esearchreslt\x2Ecom
www\x2Eweepee\x2Ecom\d+metaresults\.copernic\.com\s+
www\x2Eyok\x2Ecom\s+jupitersatellites\x2Ebiz.*User-Agent\x3Aclvompycem\x2fcen\.vcn
zmnjgmomgbdz\x2fzzmw\.gzt\d+Ready
