-i%3fUser-Agent\x3Awww\x2eproventactics\x2ecom
195\.225\.\<title\>Actual
2\x2E41\d+www\x2Erichfind\x2EcomHost\x3ABeyond
3A\d+Host\x3AHWAEUser-Agent\x3A
3A\s+URLBlazeHost\x3Atrackhjhgquqssq\x2fpjm
3Awww\x2eurlblaze\x2enetulmxct\x2fmqoycEFErrorHost\x3Ae2give\.com
666Host\x3aWEBCAM-Host\x3a
AID\x2FHost\x3aHourskl\x2Esearch\x2Eneed2find\x2EcomHost\x3aHost\x3A
Admin\s+daosearch\x2EcomMyPostwww\.raxsearch\.comref\x3D\x25user\x5Fid
Agent\s+\x2Ftoolbar\x2Fico\x2F
AnalSpy\-LockedacezSubject\x3A
Authorization\x3a\s+Host\x3a
BasicPointsHost\x3Anews
Black\s+Warezxmlns\x3A%3flinkautomatici\x2EcomSubject\x3aHost\x3A
BysooTBUser-Agent\x3A
Computer\x7D\x7BSysuptime\x3Awww\x2Eezula\x2EcomanswerServerHost\x3Aserveradfsgecoiwnf
ConnectionUser-Agent\x3A\swww\.fast-finder\.com
Cookie\x3A\x2Fimages\x2Fnocache\x2Ftr\x2Fgca\x2Fm\.gif\?
DISK\s+c\.goclick\.com\w+asdbiz\x2Ebizfrom\x7croogoo\x7cCurrentiOpusetbuviaebe\x2feqv\.bvvpjpoptwql\x2frlnj
DaysinfoBackAtTaCkwww\x2Ealfacleaner\x2Ecom
DesktopBladeclient=wwwHello\x2Exmlns\x3A
DesktopHost\x3Aact=Microsoft
DmInf\x5E\x0D\x0A\x0D\x0AAttached\x2Fbar_pl\x2Fchk\.fcgi
FCTB1\stoolbar\.anwb\.nlrichfind\x2Ecom
Flooded\s+Host\x3A\s+AppName\x2FGRSI\|Server\|Host\x3Aorigin\x3DsidefindHost\x3AUser-Agent\x3A
From\x3A\<title\>ActualUser-Agent\x3A\x2Fbar_pl\x2Ffav\.fcgi
GREATHost\x3aFILESIZE\x3E\x2Fiis2ebs\.aspFTPUser-Agent\x3A
GamespyAttachedIndyReferer\x3AToolbarCurrent\x3BCIA
Googlelog\=\x7BIP\x3APG=SPEEDBAR
HANDYHost\x3aHost\x3aHost\x3Ayddznydqir\x2feviGatornewsSoftActivity
HXDownload\s+Host\x3AArcadeHourspjpoptwql\x2frlnjFrom\x3A
HXLogOnly\w+areSubject\x3a\swww\.fast-finder\.comawbeta\.net-nucleus\.com
Host\x3AAddressDaemonUser-Agent\x3AUser-Agent\x3a
Host\x3AAttachedengineact=Download
Host\x3ADIMBUSsidebar\.activeshopper\.comUser-Agent\x3APcast
Host\x3ADesktopcargo=report\<\x2Ftitle\>Host\x3a\.fcgiupgrade\x2Eqsrch\x2Einfo
Host\x3AHost\x3AX-Mailer\x3a
Host\x3AInformationwww\x2Ezhongsou\x2EcomLitequick\x2Eqsrch\x2Ecom
Host\x3APG=SPEEDBARReferer\x3a
Host\x3ASubject\x3AFrom\x3a\xd0\xc5\xcf\xa2
Host\x3AX-Mailer\x3atoolbar\.wishbone\.com
Host\x3A\d+FTPsearch\.dropspam\.com
Host\x3A\d+Subject\x3Aas\x2Estarware\x2Ecom\x2Fdp\x2Fsearch\?x=
Host\x3A\s+Agentbody=\x2521\x2521\x2521Optix
Host\x3A\s+Online100013Agentsvr\x5E\x5EMerlin
Host\x3A\s+\x2APORT3\x2A\[DRIVEwww\.raxsearch\.comSubject\x3aHost\x3a
Host\x3A\s+jsp\s+User-Agent\x3Au=serverFILE\x2Fxml\x2Ftoolbar\x2Fcheck=at\x3a
Host\x3A\s+lnzzlnbk\x2fpkrm\.fin
Host\x3A\s+www\.iggsey\.comcs\x2Esmartshopper\x2Ecom
Host\x3A\w+User-Agent\x3AHost\x3A
Host\x3A\w+wwwfromToolbartheServer\x3Awww\x2Esearchreslt\x2Ecom
Host\x3A\x252EResultsUser-Agent\x3A
Host\x3A\x2cSTATSTimeTotalpassword\x3B1\x3BOptix
Host\x3Abacktrust\x2EcomconfigINTERNAL\.iniTrojanCurrentDaemonresultsmaster\x2EcomReportMyuntil
Host\x3AfromZC-Bridgev\x2Exml\x2FNFO\x2CRegistered
Host\x3AlogUser-Agent\x3AonSubject\x3A
Host\x3Astech\x2Eweb-nexus\x2EnetHost\x3A
Host\x3AtoUser-Agent\x3AClientsConnected-
Host\x3a===========\x3Ewww\x2Eonetoolbar\x2Ecom
Host\x3a\s+ToolBarX-Mailer\x3aUser-Agent\x3AMM_RECO\x2EEXE
Host\x3a\s+www\s+Host\x3AHost\x3AIPAsynchaveAdToolszopabora\x2EinfoHost\x3a
Host\x3anotificationwww\.thecommunicator\.net
Hours\w+User-Agent\x3AChildWebGuardian
IPAnaloffers\x2Ebullseye-network\x2Ecom
IndyHost\x3AGirlFriendReferer\x3A
InformationAgentReferer\x3AClient
InformationHost\x3Abadurl\x2Egrandstreetinteractive\x2Ecom
InformationSubject\x3ASpynovabyBlacksnprtz\x7CdialnoSearch
Iterenet\s+www\x2Emirarsearch\x2EcomHost\x3A
JMailReportgpstool\x2eglobaladserver\x2ecom
LIST\]SpamBlockerUtilityTry2FindBasicHost\x3AUser-Agent\x3AAcmeprotocolSpy
LOGLiveHost\x3ALOGHandyhttp\x3A\x2F\x2Fwww\.searchinweb\.com\x2Fsearch\.php\?said=bar
LOG\s+spyblpatHost\x3Ais\x2Ephp
LogsHXLogOnlytoolbar\x2Ei-lookup\x2Ecom
MicrosoftHost\x3ASubject\x3anamedDownloadUser-Agent\x3a
MyAgentprotocolprotocolHost\x3A\x2Fs\x28robert\x40blackcastlesoft\x2Ecom\x29data2\.activshopper\.com
MyHost\x3AtoHost\x3AWinSessionwww\x2eurlblaze\x2enetResultHost\x3A
My\x2Fdesktop\x2FWinSessionHost\x3aOnlineTPSystem\x7D\x7C
MyverToolbarTrojanControlHost\x3A
NETObserveSupervisorHost\x3Awebsearch\x2Edrsnsrch\x2Ecom
NetTracker\.htaServerTheef2trustyfiles\x2EcomlogsHost\x3Aversion
OSSProxy\d+X-Mailer\x3Abacktrust\x2Ecom
OS\x2F\d+User-Agent\x3AUser-Agent\x3A
Pass-On\w+c\.goclick\.comletter
Pleasewww\x2Ewebfringe\x2Ecom\x03\x00\x1c\x00\x00\x00\x00\x00\x01Furax
Port\s+AgentHost\x3Ainsertkeys\x3Ckeys\x40hotpop
ProAgentHost\x3aHost\x3AiOpuss_sq=aolsnssigninwininet
ProPOWRSTRPquick\x2Eqsrch\x2EcomReferer\x3A
Prodaosearch\x2EcomReferer\x3A007User-Agent\x3A
ProjectHost\x3AlogHost\x3Awww\x2Esnap\x2EcomGoogle-\>rtServidor\x2E
Ready\s+Client\s+MyBrowserHost\x3asecurityon\x3AHost\x3ARedirector\x22ServerHost\x3AX-Mailer\x3A
Referer\x3aHost\x3aport\x3aactivity
Remote\x3Cchat\x3EX-Mailer\x3awww\x2eproventactics\x2ecom
RequestWindowszzzvmkituktgr\x2fetieencoder
RequestedLoggedtb\x2Efreeprod\x2EcomHWAESubject\x3aadserver\.warezclient\.com
Root\s+insert\s+haveFTUser-Agent\x3ADayspassword\x3B0\x3BIncorrectClientsConnected-Host\x3A\x2APORT3\x2A
RootviewNetControl\x2EServerdata2\.activshopper\.com
SAcc\d+Seconds\-\x2Fcommunicatortb
SI\|Server\|\s+OSSProxy\x5Chome\/lordofsearch%3fAuthorization\x3a
SecureNet\s+hostiedesksearch\.dropspam\.com
Send=\s+User-Agent\x3A\s+LoginHost\x3a\x2Ffriendship\x2Femail_thank_you\?Host\x3aCenterSubject\x3A
ServerHost\x3Atid\x3D\x25toolbar\x5Fidcomtrustyfiles\x2Ecom
ServerOVNsearch2\.ad\.shopnav\.com\x2F9899\x2Fsearch\x2Fresults\.php
Server\.exeHWPEServer\x3aHost\x3A
Server\d+dcww\x2Edmcast\x2EcomdistID=Host\x3aSubject\x3A
Server\x2Fdownload\x2Ftoolbar\x2Flocatorstoolbar\x2Ehtml%3fSubject\x3AEveryware
Server\x3AWordTheHost\x3afrom
ShadowNet\s+AID\x2FUser-Agent\x3AFen\xeatreEye\x2Fdss\x2Fcc\.2_0_0\.
Softwarerequestedoffers\x2Ebullseye-network\x2Ecom
Stealthwww\x2Emyarmory\x2Ecomresultsmaster\x2Ecom
Subject\x3AKeyloggerSAHHost\x3ASurveillancenotification\x2Fdownload\x2Ftoolbar\x2Flocatorstoolbar
Subject\x3AUser-Agent\x3AiebarSubject\x3A
Subject\x3A\d+AgentUser-Agent\x3ahasHost\x3a
Subject\x3A\d+media\x2Edxcdirect\x2Ecom\.smx\?PASSW=SAHHost\x3A
Subject\x3A\s+www\x2eproventactics\x2ecomdownloads\x2Emorpheus\x2Ecom\x2Frotation
Subject\x3aPorta\x2Fasp\x2Foffers\.asp\?\x2Fiis2ebs\.aspwww\x2Esmileycentral\x2Ecom
Subject\x3a\s+Yeah\!Online\x2521\x2521\x2521
TPSystemHost\x3AHost\x3ashow\x2Eroogoo\x2EcomX-Mailer\x3A
TSA\x2FS\x3aUsers\x5chttp\x3A\x2F\x2Ftv\x2Eseekmo\x2Ecom\x2Fshowme\x2Easpx\x3Fkeyword=
Theef2offers\x2Ebullseye-network\x2Ecom
ToolbarUser-Agent\x3AFrom\x3A
Toolbar\s+pjpoptwql\x2frlnjSubject\x3A
Toolbar\w+SoftActivitypassword\x3B0\x3BIncorrect
Toolbar\w+www\x2Etopadwarereviews\x2Ecommedia\x2Etop-banners\x2Ecom
Toolbar\x2Fimages\x2Fnocache\x2Ftr\x2Fgca\x2Fm\.gif\?
Try2Find\x23\x23\x23\x23ToolbarServerUser\x3A
UI2AgentConnectedDesktopSubject\x3Aixqshv\x2fqzccsactualnames\.com
URL\s+\.cfgmPOPrtCUSTOMPalToolbarUser-Agent\x3A
Uin=encodernotification\x2Ftoolbar\x2FHost\x3AUser-Agent\x3A
User-Agent\x3A3AHelpAgent\x3AHost\x3AsearchresltHost\x3Anotification
User-Agent\x3AHost\x3a\x22The
User-Agent\x3AMailerGuarded
User-Agent\x3ASpyPORT-ischeck=Component
User-Agent\x3ASurveillancecomOnline
User-Agent\x3AUser-Agent\x3a
User-Agent\x3A\s+BossUser-Agent\x3ASpediaUser-Agent\x3A
User-Agent\x3A\s+GETwww\x2Eoemji\x2Ecom
User-Agent\x3A\s+Host\x3Acdpnode=FILESIZE\x3Etoolsbar\x2Ekuaiso\x2Ecom
User-Agent\x3A\s+Robert
User-Agent\x3A\s+\x7D\x7BPassword\x3AAnal
User-Agent\x3A\s+xbqyosoe\x2fcpvmAdToolsconnectedNodes
User-Agent\x3A\w+Minutes\d+www\x2Eeblocs\x2EcomHost\x3ARunnerHost\x3a\x2Ehtmldll\x3F
User-Agent\x3A\w+Owner\x3A\w+Wordixqshv\x2fqzccsServer\x00MyBYReferer\x3Awww\x2Eccnnlc\x2Ecom\x04\x00
User-Agent\x3A\w+data2\.activshopper\.comdll\x3F
User-Agent\x3A\x2Ftba\x2FFrom\x3A
User-Agent\x3Aregister\.aspUser-Agent\x3AHost\x3AcdpView
User-Agent\x3Aupgrade\x2Eqsrch\x2Einfo
User-Agent\x3Awww\x2Emyarmory\x2EcomHost\x3AUser-Agent\x3aHost\x3AportAuthorization\x3a\x2Fnewsurfer4\x2F
User-Agent\x3aHost\x3AHost\x3ASpyBuddy
User-Agent\x3aHost\x3Apasswordhavewww\x2Ealfacleaner\x2Ecom
User-Agent\x3a\x2Fnewsurfer4\x2F
Version\s+User-Agent\x3Abindmqnqgijmng\x2foj
Wareztv\x2Eseekmo\x2Ecom\sKeyloggingTRUSTYFILES\x2ECOM
We\d+pjpoptwql\x2frlnjX-Mailer\x3a
WindowsFrom\x3A\x2FCU1\-extreme\x2Ebiz
Windows\x2Fclient\x2FBlackreportc\.goclick\.comX-Sender\x3A
Word\s+ExploiterSchwindler\x2Fr\x2Fkeys\x2Fkeys
Word\s+User-Agent\x3awww\x2Esogou\x2Ecom
X-Mailer\x3A\s+ToolbarScanerX-Mailer\x3AInformation
X-Mailer\x3A\s+Toolbar\s+supremetoolbar\.comst=Host\x3A\x5Chome\/lordofsearchMicrosoftHost\x3a\+The\+password\+is\x3A
X-Mailer\x3aReferer\x3Asponsor2\.ucmore\.com
X-Mailer\x3aSpyAgentRootHost\x3A
Xtrawww\x2Einstafinder\x2EcomsearchHost\x3A
YWRtaW46cGFzc3dvcmQ\s+www\x2Ealfacleaner\x2Ecom
Yeah\!User-Agent\x3a
ZC-BridgeHost\x3ASubject\x3aas\x2Estarware\x2Ecom
ZC-Bridge\s+www\x2Ewebcruiser\x2Ecc\x22StealthReferer\x3AContact
\.cfg\x2Fsearchfast\x2F\x22007A-SpyWebsitehttp\x3A\x2F\x2Fsupremetoolbar\.com\x2Findex\.php\?tpid=
\/cgi-bin\/PopupVHost\x3Apiolet\x0D\x0A\x0D\x0AAttached
\sKeylogging\s+ApofisToolbar
\x22reaction\x2Etxt\x22\d+sErverdist\x2Eatlas\x2Dia\x2EcomUser-Agent\x3A
\x23\x23\x23\x23Host\x3ASubject\x3Awww\x2Epcsentinelsoftware\x2EcomHost\x3AWeHost\x3awww\x2Ewowokay\x2Ecom/wowokaybar\x2Ephp
\x28BDLL\x29Googledll\x3F
\x2APORT2\x2A\w+Host\x3a\s+jspIDENTIFYserverHOST\x3ASubject\x3Ai\-femdom\x2EcomUser-Agent\x3Alog\=\x7BIP\x3A
\x2Easpx\s+www\x2Ealtnet\x2EcomSubject\x3A
\x2Etxt\stoolbar\.anwb\.nlHost\x3AiOpusA-311Servert=form-data\x3B\x20name=\x22pid\x22
\x2Fbar_pl\x2Fchk\.fcgiHost\x3a
\x2Fbar_pl\x2Fchk_bar\.fcgiUser-Agent\x3A
\x2Fbar_pl\x2Fchk_bar\.fcgi\s+adblock\x2Elinkz\x2Ecom
\x2Fbar_pl\x2Fshdoclc\.fcgi\w+Referer\x3A\d+\x2Fbar_pl\x2Fshdoclc\.fcgiareHost\x3A
\x2Fnewsurfer4\x2FOK\r\nencodertvlistingsTM_SEARCH3
\x2Frssupdate\.cgiToolbarsearch\.dropspam\.com
\x2Fsearchfast\x2FNavhelper
\x2Fta\x2FNEWS\x2F\d+Toolbarwww\x2Eonlinecasinoextra\x2Ecom
\x2Fxml\x2Ftoolbar\x2F
\x3BCIAKeylogger-ProHost\x3aproductscs\x2Eshopperreports\x2Ecom
\x3Cchat\x3EHost\x3Atid\x3D\x7B
\x3Clogs\x40dummyserver\x2Ecom\x3E
\x5BStatic\w+www\.iggsey\.comUser-Agent\x3AX-Mailer\x3aComputer
\x5D\x2520\x5BPort_\d+TM_SEARCH3engineto=\x2Fezsb\s\x3A
\x7D\x7BPassword\x3ADesktopDownloadfowclxccdxn\x2fuxwn\.ddy
\x7D\x7BTrojan\x3A\w+Host\x3Arprpgbnrppb\x2fci
\x7D\x7BTrojan\x3A\w+by\w+dddlogin\x2Edudu\x2EcomSurveillanceIPOblivionhoroscope
\x7D\x7BUser\x3A\d+Host\x3AUser-Agent\x3Aadblock\x2Elinkz\x2Ecom
\x7D\x7BUser\x3A\x7D\x7BTrojan\x3ASPYSubject\x3A\swww\.fast-finder\.comhostieLogger
\x7croogoo\x7cTestiufilfwulmfi\x2friuf\.lioHeaders
about\d+yxegtd\x2fefcwgHost\x3ATPSystemwww\x2Ee-finder\x2Ecc
action\x2EpioletHost\x3AIP-www\x2Einternetadvertisingcompany\x2Ebiz
actualnames\.com\s+fast-look\x2Ecomwww\x2Emaxifiles\x2Ecom
adblock\x2Elinkz\x2Ecomwww\.iggsey\.comHost\x3A
adfsgecoiwnf\d+Host\x3aTCP\x2FAD\x2FULOGNetBus
ads\.grokads\.com\s+deskwizz\x2Ecom
asdbiz\x2Ebiz\s+HWAEUser-Agent\x3ATheef2
asdbiz\x2Ebiz\s+informationHost\x3A
at\w+Pre\s+adfsgecoiwnfhirmvtg\x2fggqh\.kqhSurveillanceHost\x3A
bar\-navig\x2Eyandex\x2Eru\s+
configINTERNAL\.inikwdwww\x2Ewordiq\x2Ecomas\x2Estarware\x2Ecom
corep\x2Edmcast\x2Ecom\s+FunWebProducts\w+searchreslt\x7D\x7BSysuptime\x3ASubject\x3AHANDY
cs\x2Eshopperreports\x2EcomActivityHost\x3AYeah\!User-Agent\x3AMicrosoft
cyber@yahoo\x2Ecom\s+Host\x3a\x7D\x7Crichfind\x2Ecom
data\.warezclient\.comoakmanympnw\x2flnkd\.pkHost\x3AScaner
dialup\x5fvpn\x40hermangroup\x2EorgUser-Agent\x3A
dialupvpn\x5fpwd\s+HXDownloadupdailyinformation
dialupvpn\x5fpwd\w+tvlistings\s+fowclxccdxn\x2fuxwn\.ddywww\x2evirusprotectpro\x2ecom\stoolbar\.anwb\.nl
dl\x2Eweb-nexus\x2Enet\d+www\x2Eonlinecasinoextra\x2Ecomsqlads\.grokads\.com
doarauzeraqf\x2fvvv\.ul
download\x2Eeblocs\x2EcomHost\x3AReferer\x3A
downloadfile\x2eorg\w+com\x3EHost\x3A
e2give\.comADRemoteHost\x3A
e2give\.comConnectionSpywww\x2Eslinkyslate
encoder\s+cyber@yahoo\x2Ecomcu
error\*\-\*Wrong\s+www\x2Ewordiq\x2Ecom\s+Subject\x3AAlexaOnline\x2521\x2521\x2521User-Agent\x3A
eveocczmthmmq\x2fomzl\s+zmnjgmomgbdz\x2fzzmw\.gzt
filename=\x22\s+www\x2Epeer2mail\x2Ecomgot
frame_ver2\s+communityLibrarySoftwareWinCrashcomHost\x3Atid\x3D\x25toolbar\x5Fid
fsbuff\s+User-Agent\x3Afrom\x3A
gpstool\x2eglobaladserver\x2ecomfriend_nickname=CIA-Notify-Tezt
hirmvtg\x2fggqh\.kqh\w+whenu\x2Ecom\w+weatherHost\x3AUser-Agent\x3A
horoscope2Cookie\x3adatATTENTION\x3AKontiki
http\x3A\x2F\x2Fwww\.searchinweb\.com\x2Fsearch\.php\?said=bar
installs\x2Eseekmo\x2Ecom\s+spyblini\x2EiniUpdateUser-Agent\x3A
is\w+gdvsotuqwsg\x2fdxt\.hd
iz=Referer\x3Aoffers\x2Ebullseye-network\x2Ecom
libManager\x2Edll\x5Eget
log\=\x7BIP\x3A\s+Pcast\d+Host\x3aohgdhkzfhdzo\x2fuwpOK\r\nHost\x3AHWAEname\x2ecnnic\x2ecnRXnewads1\x2Ecom
myway\.com\s+SupervisorPalUser-Agent\x3ASearch
nethttp\x3A\x2F\x2FsupremetoolbarPORT\x3D
news\d+Host\x3A\d+Spywww\x2Eemp3finder\x2Ecomwwwvbclient\x3DSpyBuddyZOMBIES\x5fHTTP\x5fGETearch\x2Eearthlink
nick_name=CIA-Testsearchnuggetprotocolframe_ver2MailerToolbarUser-Agent\x3afromEnTrY
onBetaHost\x3ayouRootReferer\x3A
on\s+dist\x2Eatlas\x2Dia\x2Ecom
on\w+Host\x3AComputerKeylogger\x2EcomHost\x3AUser-Agent\x3A
ookflolfctm\x2fnmot\.fmu
ovplEchelonUser-Agent\x3AUser-Agent\x3AHost\x3a
ovpl\w+UBAgent%3fSchwindlerurl=Host\x3ahttpUser-Agent\x3A
pass=Referer\x3ASurveillance
passcorrect\x3B\s+\x2Fcbn\x2Fnode=Host\x3A\x3Fsearch\x3Dversion
port\s+aresflashdownloader\x2Ecom\s+adfsgecoiwnf\x23\x23\x23\x23User-Agent\x3A
ppcdomain\x2Eco\x2EukBasic
ppcdomain\x2Eco\x2Euk\s+ready\w+PARSERHost\x3aA-311ServerUser-Agent\x3Ascn\x2emystoretoolbar\x2ecom
protocolNetControl\x2EServerKEYLOGGERUser-Agent\x3A
rank\x2Etoolbarbrowser\x2Ecomlnzzlnbk\x2fpkrm\.fin
ref\x3D\x25user\x5Fid\d+\x2Fbar_pl\x2Fchk\.fcgi
report\<\x2Ftitle\>Referer\x3Aaresflashdownloader\x2EcomHost\x3ADeathpioletLOGtowww\x2Esearchexpert\x2Ecom
richfind\x2EcomCookie\x3aName=Your\+Host\+is\x3A
richfind\x2Ecomdcww\x2Edmcast\x2Ecom
sbRedirectionsHost\x3AHost\x3AUser-Agent\x3Ahotbar%3fwww\x2Einternetadvertisingcompany\x2Ebiz
search\x2econduit\x2ecom\d+sidebar\.activeshopper\.comUser-Agent\x3A
search\x2eimesh\x2ecom\s+WatchDogupwww\.klikvipsearch\.com
seqepagqfphv\x2fsfdX-Mailer\x3A
source%3Dultrasearch136%26campaign%3DsnapuplogWinInet3Azopabora\x2Einfo
t=ProtoUser-Agent\x3Aquick\x2Eqsrch\x2Ecom
tb\x2Efreeprod\x2Ecom\s+Web\.fcgiclvompycem\x2fcen\.vcn
throughpjpoptwql\x2frlnjPOSTwebsearch\.getmirar\.comHost\x3Awww\x2EZSearchResults\x2EcomX-Mailer\x3A
to\d+User-Agent\x3AFiltered
toc=MicrosoftStartupStarLoggerServerX-Mailer\x3a
toolbar_domain_redirectriggiymd\x2fwdhi\.vhi
twfofrfzlugq\x2feve\.qdSeconds\-
u=with\x3AHBand,Deathhoroscope2
update\.cgi\s+wwwProbnymomspyo\x2fzowy
v=c=DALOGbacktrust\x2EcomHost\x3AConnectedHost\x3AHost\x3aHost\x3alsSpyDawn
v\x2E\s+ocllceclbhs\x2fgth\w+http\x3A\x2F\x2Fwww\.searchinweb\.com\x2Fsearch\.php\?said=bar
versionIDENTIFYstarted\x2EUser-Agent\x3A
weather2ResultX-Sender\x3A
welcome\s+Host\x3A\s+ThistoIpHost\x3Abadurl\x2Egrandstreetinteractive\x2Ecom
welcomeforToolbarHost\x3A
wjpropqmlpohj\x2flo\d+Host\x3AUser-Agent\x3A
wjpropqmlpohj\x2flo\s+media\x2Edxcdirect\x2Ecom
wv=update\.cgidrivesDaysform-data\x3B\x20name=\x22pid\x22
www\.123mania\.comSubject\x3APromulGate666Logger-iVisicom
www\.thecommunicator\.net\d+http\x3A\x2F\x2Ftv\x2Eseekmo\x2Ecom\x2Fshowme\x2Easpx\x3Fkeyword=
www\.trackhits\.ccUser-Agent\x3Aiz=LOGSupremeResult
www\s+X-Mailer\x3aSpyBuddyUser-Agent\x3A
www\x2Ealtnet\x2EcomHost\x3ANSIS_DOWNLOADSubject\x3AUser-Agent\x3Awww\x2Esearchingall\x2Ecom
www\x2Edotcomtoolbar\x2Ecom\d+DesktopAddressIDENTIFY
www\x2Emaxifiles\x2EcomServidor\x2E
www\x2Eonlinecasinoextra\x2EcomWindows
www\x2Epcsentinelsoftware\x2Ecom
www\x2Epurityscan\x2Ecom\s+from\.myway\.comToolbarUI2
www\x2Esearchexpert\x2Ecom\d+Referer\x3Adatcouponbar\.coupons\.com
www\x2Esogou\x2Ecom\s+HWAE\+The\+password\+is\x3A
www\x2Eweepee\x2Ecom\s+www\x2Ewebfringe\x2Ecomwww\.123mania\.com\x2F0409
www\x2Ezhongsou\x2Ecom\w+FTX-Mailer\x3A
www\x2e2-seek\x2ecom\x2fsearchUser-Agent\x3a
xbqyosoe\x2fcpvmviewComponentisrelated\x2Eyok\x2Ecom
xbqyosoe\x2fcpvmwww\x2eurlblaze\x2enetconfigINTERNAL\.ini
yddznydqir\x2feviaresflashdownloader\x2Ecom
zmnjgmomgbdz\x2fzzmw\.gztwww3\.addfreestats\.comKeylogger
zopabora\x2EinfocomhoroscopeTravelInsidefromUser-Agent\x3AFrom\x3Awww\x2EZSearchResults\x2EcomExplorer
zzzvmkituktgr\x2fetie\s+WindowsAttachedPalas\x2Estarware\x2Ecom\x2Fdp\x2Fsearch\?x=
