package LTLparser;

/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;

class TokenVal {
  // fields
    int linenum;
    int charnum;
  // constructor
    TokenVal(int line, int ch) {
        linenum = line;
        charnum = ch;
    }
}

class IdTokenVal extends TokenVal {
  // new field: the value of the identifier
    String idVal;
  // constructor
    IdTokenVal(int line, int ch, String val) {
        super(line, ch);
    idVal = val;
    }
}

class ExpTokenVal extends TokenVal {
  // new field: the value of the string literal
    String expVal;
  // constructor
    ExpTokenVal(int line, int ch, String val) {
        super(line, ch);
        expVal = val;
    }
}

// the current token starts on its line.
class CharNum {
    static int num=1;
}

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>LTLparser.jlex</tt>
 */
public class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\4\1\57\1\57\1\57\22\0\1\3\1\50\1\11"+
    "\3\0\1\51\1\7\1\44\1\45\1\52\1\54\1\0\1\56\1\0"+
    "\1\5\12\1\2\0\1\46\1\0\1\47\1\7\1\0\5\1\1\43"+
    "\1\40\5\1\1\36\4\1\1\35\2\1\1\33\1\35\1\34\1\37"+
    "\2\1\1\41\1\6\1\42\1\55\1\1\1\0\1\21\3\2\1\17"+
    "\1\20\2\2\1\26\2\2\1\22\1\27\1\10\1\2\1\30\1\31"+
    "\1\15\1\23\1\14\1\16\1\32\1\24\1\2\1\25\1\2\1\12"+
    "\1\53\1\13\7\0\1\57\u1fa2\0\1\57\1\57\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\2\1\2\5\6\2"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\1\1\14"+
    "\1\15\1\16\1\1\1\17\2\20\2\21\1\22\1\1"+
    "\1\23\1\24\1\23\1\24\6\2\1\25\1\26\1\0"+
    "\1\27\1\23\6\2\1\30\1\23\1\31\1\32\5\2"+
    "\1\0\1\31\1\33\1\2\1\34\2\2\2\23\1\2"+
    "\1\35\2\2\1\36\2\2\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\60\0\300\0\360\0\u0120"+
    "\0\u0150\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\60"+
    "\0\60\0\60\0\60\0\60\0\60\0\u02a0\0\60\0\60"+
    "\0\60\0\u02d0\0\60\0\u0300\0\60\0\u0330\0\60\0\60"+
    "\0\u0360\0\u0390\0\60\0\u03c0\0\u0150\0\u03f0\0\u0420\0\u0450"+
    "\0\u0480\0\u04b0\0\u04e0\0\60\0\60\0\u0510\0\60\0\u0540"+
    "\0\u0570\0\u05a0\0\u05d0\0\u0600\0\u0630\0\u0660\0\60\0\u0690"+
    "\0\60\0\140\0\u06c0\0\u06f0\0\u0720\0\u0750\0\u0780\0\u07b0"+
    "\0\u07e0\0\140\0\u0810\0\140\0\u0840\0\u0870\0\u07e0\0\u08a0"+
    "\0\u08d0\0\140\0\u0900\0\u0930\0\140\0\u0960\0\u0990\0\140";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\1\3\1\4\1\5\1\6\1\7\1\2\1\3"+
    "\1\10\1\11\1\2\1\12\1\3\1\13\1\14\1\15"+
    "\1\16\4\3\1\17\4\3\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\2\1\27\1\30\1\31\1\32"+
    "\1\2\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\62\0\2\3\5\0\1\3\3\0\25\3\2\0\1\3"+
    "\17\0\1\4\62\0\1\35\56\0\1\37\52\0\4\10"+
    "\1\0\1\10\1\42\2\10\1\43\46\10\4\11\1\0"+
    "\1\11\1\44\2\11\1\0\1\11\1\45\44\11\1\0"+
    "\2\3\5\0\1\3\3\0\1\3\1\46\23\3\2\0"+
    "\1\3\15\0\2\3\5\0\1\47\3\0\25\3\2\0"+
    "\1\3\15\0\2\3\5\0\1\3\3\0\15\3\1\50"+
    "\7\3\2\0\1\3\15\0\2\3\5\0\1\3\3\0"+
    "\5\3\1\51\17\3\2\0\1\3\15\0\2\3\5\0"+
    "\1\3\3\0\6\3\1\52\16\3\2\0\1\3\15\0"+
    "\2\3\5\0\1\3\3\0\13\3\1\53\11\3\2\0"+
    "\1\3\56\0\1\54\64\0\1\55\6\0\1\56\52\0"+
    "\1\35\61\0\1\37\53\0\1\57\10\0\4\60\1\0"+
    "\1\60\4\10\2\60\1\10\47\60\1\0\1\60\4\11"+
    "\2\60\1\11\43\60\1\0\2\3\5\0\1\3\3\0"+
    "\2\3\1\61\22\3\2\0\1\3\15\0\2\3\5\0"+
    "\1\3\3\0\1\62\24\3\2\0\1\3\15\0\2\3"+
    "\5\0\1\3\3\0\2\3\1\63\22\3\2\0\1\3"+
    "\15\0\2\3\5\0\1\3\3\0\6\3\1\64\16\3"+
    "\2\0\1\3\15\0\2\3\5\0\1\3\3\0\10\3"+
    "\1\65\14\3\2\0\1\3\15\0\2\3\5\0\1\3"+
    "\3\0\14\3\1\66\10\3\2\0\1\3\63\0\1\67"+
    "\10\0\4\60\1\0\1\60\1\70\2\60\1\71\46\60"+
    "\1\0\2\3\5\0\1\3\3\0\3\3\1\72\21\3"+
    "\2\0\1\3\15\0\2\3\5\0\1\3\3\0\12\3"+
    "\1\73\12\3\2\0\1\3\15\0\2\3\5\0\1\3"+
    "\3\0\12\3\1\74\12\3\2\0\1\3\15\0\2\3"+
    "\5\0\1\3\3\0\7\3\1\75\15\3\2\0\1\3"+
    "\15\0\2\3\5\0\1\3\3\0\5\3\1\76\17\3"+
    "\2\0\1\3\15\0\2\3\5\0\1\3\3\0\6\3"+
    "\1\77\16\3\2\0\1\3\14\0\4\100\1\0\1\100"+
    "\3\60\1\101\2\100\1\60\43\100\1\0\2\3\5\0"+
    "\1\3\3\0\6\3\1\102\16\3\2\0\1\3\15\0"+
    "\2\3\5\0\1\3\3\0\16\3\1\103\6\3\2\0"+
    "\1\3\15\0\2\3\5\0\1\3\3\0\3\3\1\104"+
    "\21\3\2\0\1\3\15\0\2\3\5\0\1\3\3\0"+
    "\11\3\1\105\13\3\2\0\1\3\15\0\2\3\5\0"+
    "\1\3\3\0\12\3\1\106\12\3\2\0\1\3\14\0"+
    "\4\100\1\0\4\100\1\71\46\100\4\107\1\0\1\107"+
    "\1\110\2\107\1\0\46\107\1\0\2\3\5\0\1\3"+
    "\3\0\5\3\1\111\17\3\2\0\1\3\15\0\2\3"+
    "\5\0\1\3\3\0\7\3\1\112\15\3\2\0\1\3"+
    "\15\0\2\3\5\0\1\3\3\0\3\3\1\113\21\3"+
    "\2\0\1\3\22\0\4\107\2\0\1\107\44\0\2\3"+
    "\5\0\1\3\3\0\6\3\1\114\16\3\2\0\1\3"+
    "\15\0\2\3\5\0\1\3\3\0\7\3\1\115\15\3"+
    "\2\0\1\3\15\0\2\3\5\0\1\3\3\0\3\3"+
    "\1\116\21\3\2\0\1\3\15\0\2\3\5\0\1\117"+
    "\3\0\25\3\2\0\1\3\15\0\2\3\5\0\1\3"+
    "\3\0\1\120\24\3\2\0\1\3\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2496];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\12\1\6\11\1\1\3\11"+
    "\1\1\1\11\1\1\1\11\1\1\2\11\2\1\1\11"+
    "\10\1\2\11\1\0\1\11\7\1\1\11\1\1\1\11"+
    "\6\1\1\0\20\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 188) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { return new Symbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { ErrMsg.fatal(yyline+1, CharNum.num,
                         "illegal character ignored: " + yytext());
            CharNum.num++;
            }
          case 32: break;
          case 2: 
            { Symbol S = new Symbol(sym.ID, 
                             new IdTokenVal(yyline+1, CharNum.num, yytext()));
            CharNum.num += yytext().length();
            return S;
            }
          case 33: break;
          case 3: 
            { CharNum.num += yytext().length();
            }
          case 34: break;
          case 4: 
            { CharNum.num = 1;
            }
          case 35: break;
          case 5: 
            { // unterminated expression
            ErrMsg.fatal(yyline+1, CharNum.num,
                         "unterminated embedded expression ignored");
            }
          case 36: break;
          case 6: 
            { Symbol S = new Symbol(sym.UNTIL, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 37: break;
          case 7: 
            { Symbol S = new Symbol(sym.WEAKUNTIL, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 38: break;
          case 8: 
            { Symbol S = new Symbol(sym.RELEASE, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 39: break;
          case 9: 
            { Symbol S = new Symbol(sym.STRONGRELEASE, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 40: break;
          case 10: 
            { Symbol S = new Symbol(sym.NEXT, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 41: break;
          case 11: 
            { Symbol S = new Symbol(sym.ALWAYS, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 42: break;
          case 12: 
            { Symbol S = new Symbol(sym.EVENTUALLY, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 43: break;
          case 13: 
            { Symbol S = new Symbol(sym.LPAREN, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 44: break;
          case 14: 
            { Symbol S = new Symbol(sym.RPAREN, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 45: break;
          case 15: 
            { Symbol S = new Symbol(sym.NEGATION, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 46: break;
          case 16: 
            { Symbol S = new Symbol(sym.AND, new TokenVal(yyline+1, CharNum.num));
            CharNum.num+=2;
            return S;
            }
          case 47: break;
          case 17: 
            { Symbol S = new Symbol(sym.OR, new TokenVal(yyline+1, CharNum.num));
            CharNum.num+=2;
            return S;
            }
          case 48: break;
          case 18: 
            { Symbol S = new Symbol(sym.XOR, new TokenVal(yyline+1, CharNum.num));
            CharNum.num+=2;
            return S;
            }
          case 49: break;
          case 19: 
            { // bad escape character
            ErrMsg.fatal(yyline+1, CharNum.num,
             "unterminated embedded expression with bad escaped character ignored");
            }
          case 50: break;
          case 20: 
            { String expVal = yytext();
            Symbol S = new Symbol(sym.EXP,
                             new ExpTokenVal(yyline+1, CharNum.num, expVal));
            CharNum.num += yytext().length();
            return S;
            }
          case 51: break;
          case 21: 
            { Symbol S = new Symbol(sym.ALWAYS, new TokenVal(yyline+1, CharNum.num));
            CharNum.num+=2;
            return S;
            }
          case 52: break;
          case 22: 
            { Symbol S = new Symbol(sym.EVENTUALLY, new TokenVal(yyline+1, CharNum.num));
            CharNum.num+=2;
            return S;
            }
          case 53: break;
          case 23: 
            { Symbol S = new Symbol(sym.IMPLICATION, new TokenVal(yyline+1, CharNum.num));
            CharNum.num+=2;
            return S;
            }
          case 54: break;
          case 24: 
            { Symbol S = new Symbol(sym.EQUIVALENCE, new TokenVal(yyline+1, CharNum.num));
            CharNum.num+=3;
            return S;
            }
          case 55: break;
          case 25: 
            { // bad escape character
            ErrMsg.fatal(yyline+1, CharNum.num,
                         "embedded expression with bad escaped character ignored");
            CharNum.num += yytext().length();
            }
          case 56: break;
          case 26: 
            { Symbol S = new Symbol(sym.TRUE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 57: break;
          case 27: 
            { Symbol S = new Symbol(sym.UNTIL, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 58: break;
          case 28: 
            { Symbol S = new Symbol(sym.FALSE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 59: break;
          case 29: 
            { Symbol S = new Symbol(sym.ALWAYS, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 60: break;
          case 30: 
            { Symbol S = new Symbol(sym.IMPLICATION, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 61: break;
          case 31: 
            { Symbol S = new Symbol(sym.EQUIVALENCE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
