100013Agentsvr\x5E\x5EMerlinIPBeta\s\x3E\x3C
3AFrom\x3Adddrep\x2Edudu\x2Ecomform-data\x3B\x20name=\x22pid\x22
AdTools\sdownloadfile\x2eorg\w+com\x3E[^\n\r]*as\x2Estarware\x2EcomOS\x2FSSKCstech\x2Eweb-nexus\x2Enet
AgentanswerHost\x3Atool\x2Eworld2\x2EcnTCwhenu\x2Ecom
ApofisAgentFunWebProductsUser-Agent\x3A
Authorization\x3a\d+lnzzlnbk\x2fpkrm\.fin
BY\s+\x22The\dUser-Agent\x3AserverUSER-Attached
BY\x7D\x7BUser\x3AHost\x3Aconnection\x2E
Basic\s+news\s+CD\x2Furl=Host\x3a
CD\x2F\.ico\x2FsLogearch195\.225\.
CMDLoginExciteSubject\x3Adownloadfile\x2eorg
CUSTOM\swww\x2Elocators\x2Ecom\d+Seconds\-
ChildWebGuardian\d+Subject\x3A
ClientsConnected-\d+online-casino-searcher\.com\s+Warezxmlns\x3A
ConectadoHost\x3aas\.cometsystems\.com
Contact\d+Host\x3A\d+MailHost\x3aMSNLOGOVNUsertooffers\x2Ebullseye-network\x2Ecom
Cookie\x3a.*Host\x3A.*ldap\x3A\x2F\x2F
DA\dwww\x2Ee-finder\x2Ecc.*User-Agent\x3A
Days\s+HWAE\s+Host\x3APortawww\.thecommunicator\.net
Download\d+ocllceclbhs\x2fgth
Download\s+report\<\x2Ftitle\>\s+User-Agent\x3A
EFError.*Host\x3A\swww\x2emalware-stopper\x2ecom
EI.*to\s+AppName\x2FGRSI\|Server\|Host\x3Aorigin\x3Dsidefind
Everyware.*Email.*Host\x3Astepwww\x2Ekornputers\x2Ecom
FTP\s+\x2FNFO\x2CRegistered\s+Server\s+www\x2Einternet-optimizer\x2Ecom
FTP\s+\x7D\x7BPort\x3A\s+Host\x3A
From\x3A\w+SoftActivity\d+
GREAT\d+X-Mailer\x3a\d+url=enews\x2Eearthlink\x2Enet
GmbH\d+Host\x3A\w+adblock\x2Elinkz\x2EcomUser-Agent\x3Aemail
Google\s+jupitersatellites\x2Ebiz\s+Eyewww\x2Eccnnlc\x2Ecom
Guarded\s+3A\s+data2\.activshopper\.comUser-Agent\x3A
HANDY\s+Exploiter\w+\x2Fr\x2Fkeys\x2FkeysS\x3aUsers\x5cIterenet
HBand,\sHost\x3A[^\n\r]*lnzzlnbk\x2fpkrm\.fin
HWAE.*wowokay\s%3fsearchresltX-Mailer\x3AisSubject\x3a
HWPE[^\n\r]*Basic.*LOGsearches\x2Eworldtostart\x2Ecom
HXLogOnlyDaemonactivityIterenetFrom\x3AClass
Handyst=ClassStopperHost\x3ASpamBlockerUtility
Hello\x2E\s+ovpl\s+Host\x3AWeHost\x3awww\x2Ewowokay\x2Ecom/wowokaybar\x2Ephp
Host\x3A.*NETObserve\d+Host\x3aohgdhkzfhdzo\x2fuwpOK\r\n
Host\x3A.*Toolbar\s+Host\x3A
Host\x3A.*User-Agent\x3a\sRequest
Host\x3A.*rt[^\n\r]*Host\x3AUser-Agent\x3A
Host\x3A.*www\x2e2-seek\x2ecom\x2fsearch
Host\x3A00000www\x2Ezhongsou\x2Ecom
Host\x3A1\-extreme\x2EbizX-Mailer\x3awww\x2Ewebcruiser\x2Ecc
Host\x3AFrom\x3aUser-Agent\x3A\x2Fr\x2Fkeys\x2FkeysClient
Host\x3AHost\x3AFrom\x3a\x03\x00\x1c\x00\x00\x00\x00\x00\x01Furaxbnymomspyo\x2fzowy
Host\x3AHost\x3Aalertseqepagqfphv\x2fsfd
Host\x3ASubject\x3Awhenu\x2EcomHost\x3Awww\x2Evip-se\x2Ecom
Host\x3ATest\x3C\x2Fchat\x3EResultsSubject\x3A
Host\x3A[^\n\r]*\x2Fbar_pl\x2Fshdoclc\.fcgi
Host\x3A[^\n\r]*cache\x2Eeverer\x2Ecom\s+from\.myway\.comToolbar
Host\x3A\d+Subject\x3A[^\n\r]*Seconds\-ovplHost\x3AHost\x3ADownload
Host\x3A\d+UI2.*areprotocolhttp\x3A\x2F\x2Fwww\.searchinweb\.com\x2Fsearch\.php\?said=bar
Host\x3A\d+\.compress.*sidebar\.activeshopper\.com
Host\x3A\d+ver\d+sportsUBAgent
Host\x3A\dKeylogger.*Onetrustyfiles\x2Ecom
Host\x3A\dName=Your\+Host\+is\x3A.*has\s+ComputerKeylogger\x2EcomHost\x3A
Host\x3A\s+Basic\s+\.htaServerTheef2
Host\x3A\s+Boss\s+media\x2Etop-banners\x2Ecom
Host\x3A\s+Online\s+ocllceclbhs\x2fgth
Host\x3A\s+User-Agent\x3A\s+Host\x3ADesktopBlade
Host\x3A\s+\x2Ftoolbar\x2Fico\x2F\dencoderserverreport\<\x2Ftitle\>
Host\x3A\s+cyber@yahoo\x2Ecom\sWordSpy\-LockedURLBlaze
Host\x3A\s+offers\x2Ebullseye-network\x2Ecom
Host\x3A\s+twfofrfzlugq\x2feve\.qd\s+\x2Ftoolbar\x2Fsupremetb
Host\x3A\sHello\x2E.*forum=
Host\x3A\w+Toolbar\d+anHost\x3AspasHost\x3A
Host\x3A\w+User-Agent\x3A\sTeomaBarHost\x3AHoursHost\x3AHost\x3A
Host\x3A\w+www.*ToolbartheServer\x3Awww\x2Esearchreslt\x2Ecom
Host\x3A\x2Fta\x2FNEWS\x2Fyayad\x2Ecom
Host\x3Aact=Host\x3aUser-Agent\x3AUser-Agent\x3ALiteselect\x2FGet
Host\x3AconfigINTERNAL\.iniUser-Agent\x3A
Host\x3a.*ver\dRobert\dDmInf\x5EinfoSimpsonUser-Agent\x3AClientwww\x2Einternet-optimizer\x2Ecom
Host\x3a[^\n\r]*A-311\s+lnzzlnbk\x2fpkrm\.finSubject\x3aBasic
Host\x3a[^\n\r]*pgwtjgxwthx\x2fbyb\.xky[^\n\r]*source%3Dultrasearch136%26campaign%3Dsnap
Host\x3a\dATTENTION\x3A.*User-Agent\x3A
Host\x3a\s+Agent\s+Host\x3AUser-Agent\x3A\.cfgUser-Agent\x3A
Host\x3a\w+Pre.*Keyloggeradfsgecoiwnfhirmvtg\x2fggqh\.kqh
IDENTIFY.*\x2Fezsb\d+X-Mailer\x3A
IP.*encoder\d+SAHPORT-User-Agent\x3A
IPUSER-Host\x3AUser-Agent\x3A\x2Fsearchfast\x2F
Id\x3d\x5b\s+Host\x3A\s+www\x2Eyoogee\x2EcomHost\x3A\<title\>Actual
LOGGuardedHost\x3Awww\x2Esearchreslt\x2Ecomwp-includes\x2Ffeed\x2Ephp\x3F
LOG\w+PARSER\d+scn\x2emystoretoolbar\x2ecom
Logger.*aresflashdownloader\x2Ecom
Logger\w+gdvsotuqwsg\x2fdxt\.hd\dovpl\dHOST\x3AUser-Agent\x3AURLUBAgent%3fSchwindlerurl=Host\x3a
Logger\w+searchreslt\dSubject\x3AHANDY\x2FrssScaner
M\x2Ezip\d+dll\x3F\s+CodeguruBrowserwww\x2Esogou\x2Ecom
MailerHost\x3AUser-Agent\x3A
Minutes\s+\x2Fcgi\x2Flogurl\.cgi\s+e2give\.com
Mirar_KeywordContent
Monitor\s+Supervisor\s+User-Agent\x3A
NavExcel\s+dist\x2Eatlas\x2Dia\x2Ecom
OSSProxyHost\x3ASubject\x3as_sq=aolsnssignin
PASSW=\s+\x2Fta\x2FNEWS\x2F.*loomcompany\x2Ecom
PASSW=\w+www2\x2einstantbuzz\x2ecom\s+Online
Points\d+Host\x3a\dBasicwww\x2Ewebcruiser\x2Ecc
Port\x2E[^\n\r]*007\d+Logsdl\x2Eweb-nexus\x2Enet
Porta\s+SSKC\s+\.cfgmPOPrtCUSTOMPalToolbarUser-Agent\x3A
ProAgentHost\x3ALOGSeconds\-
ProjectMyWebSearchSearchAssistantfast-look\x2EcomOneReporter
ProtoSubject\x3asource\=IncrediFindProjectAgentHost\x3AHost\x3AHost\x3A
Ready[^\n\r]*User-Agent\x3A\s+Client\dFrom\x3AWebtool\x2Eworld2\x2EcnUser-Agent\x3AUser-Agent\x3a
Ready\s+Toolbar\d+ServerLiteToolbar
Ready\sver\dcount\x2Eyok\x2Ecomweather
Referer\x3AHost\x3AHost\x3ASubject\x3Aonline-casino-searcher\.comnetid=Excite
Referer\x3AUser-Agent\x3AFrom\x3AUser-Agent\x3Aadfsgecoiwnf
Referer\x3A\s+HXDownload\w+installs\x2Eseekmo\x2Ecom
Referer\x3A\s+www\x2eproventactics\x2ecom
Reports[^\n\r]*User-Agent\x3A.*largePass-Onseqepagqfphv\x2fsfd
Runner.*\x2Ehtml[^\n\r]*NetControl\x2EServer\d+media\x2Edxcdirect\x2Ecom\.smx\?PASSW=SAH
SbAts[^\n\r]*Subject\x3a\d+dcww\x2Edmcast\x2Ecom
Server\x00\s+SbAts\s+versionetbuviaebe\x2feqv\.bvv
Serverulmxct\x2fmqoycWinSession\x2Fclient\x2F\x2APORT1\x2A
Serverwjpropqmlpohj\x2floHost\x3AKEY=
Servidor\x2Ehome\x2Eedonkey\x2Ecom
ShadowNet\dsearchreslt\sTROJAN-Host\x3AYWRtaW46cGFzc3dvcmQ
Shell\x2FFileage\x7D\x7BPort\x3Aupd\x2Elop\x2Ecom
SpyAgent\d+sErver\s+User-Agent\x3A
SpyAgent\s+daosearch\x2Ecom\s+X-Mailer\x3a\s+zmnjgmomgbdz\x2fzzmw\.gzt
SpyBuddy\sPARSER.*Host\x3Aaction\x2Eforhttp\x3A\x2F\x2Fwww\.searchinweb\.com\x2Fsearch\.php\?said=bar
SpywareStrike.*Subject\x3A\s+Pcast\x2Edat\x2EToolbar
Spyware\s+ToolBar\s+User-Agent\x3AMM_RECO\x2EEXEToClientonAlert
Stablecmemailyxegtd\x2fefcwgUin=PromulGate
StarLoggerCookie\x3aHost\x3APRODUCEDwebsearch\.getmirar\.com
Stealth\x2EphpSpyAgentHost\x3AIterenetUser-Agent\x3AHost\x3AHost\x3Aorigin\x3Dsidefind
Subject\x3A.*Host\x3A\d+iz=iMeshBar%3f\x2Fbar_pl\x2Fchk_bar\.fcgi
Subject\x3A.*www\x2Ewebcruiser\x2Ecc\w+www\x2Etopadwarereviews\x2Ecom
Subject\x3AHost\x3aHost\x3A000Filelogin_ok\x5EMiniCommand
Subject\x3A[^\n\r]*Arrow[^\n\r]*whenu\x2Ecom
Subject\x3A\swww\x2Esearchwords\x2Ecom
Subject\x3a.*Host\x3a.*\x2Fproducts\x2Fspyblocs\x2F\sinternalcyber@yahoo\x2EcomHeadersRedirection
Subject\x3a\d+rprpgbnrppb\x2fci
Subject\x3a\d+zmnjgmomgbdz\x2fzzmw\.gzt
Supreme\d+Host\x3A\d+yxegtd\x2fefcwgHost\x3ATPSystem
Supreme\s+User-Agent\x3A\s+ApofisToolbarUser
SurveillanceacezHost\x3Acouponbar\.coupons\.comLOG
SystemSleuth1\x2E0versionHost\x3AArrowHost\x3a3Awebsearch\x2Edrsnsrch\x2EcomhostieiWonHost\x3apjpoptwql\x2frlnj
TM_SEARCH3Host\x3aUser-Agent\x3Amedia\x2Edxcdirect\x2Ecom
TM_SEARCH3SearchUser-Agent\x3Aas\x2Estarware\x2EcomM\x2EzipCasinoResults_sq=aolsnssignin
TOOLBAR\s+dist\x2Eatlas\x2Dia\x2Ecom
TPSystemHost\x3a\x7D\x7BUser\x3AAlert\x2Fcgi-bin\x2FX-Mailer\x3A
TROJAN-Owner\x3AUser-Agent\x3a%3fTs2\x2F
Toolbar\d+Host\x3A\d+4\x2e8\x2e4\x7D\x7BTrojan\x3Aare
User-Agent\x3A.*Host\x3A\dName=Your\+Host\+is\x3A
User-Agent\x3A.*Host\x3a\s+www\x2Ewordiq\x2Ecom\s+Subject\x3AAlexaOnline\x2521\x2521\x2521
User-Agent\x3A.*community\w+\x0d\x0asubject=GhostVoice
User-Agent\x3ABasedUser-Agent\x3A
User-Agent\x3ARunnerads\.grokads\.comHost\x3Amcndvwoemn\x2flvv\.jde
User-Agent\x3A[^\n\r]*HTTP_RAT_
User-Agent\x3A[^\n\r]*quick\x2Eqsrch\x2Ecom.*www\.searchinweb\.com
User-Agent\x3A\d+Desktop\sIDENTIFY666User-Agent\x3A\x5BStatic
User-Agent\x3A\d+Theef2\sHost\x3A
User-Agent\x3A\s+GET\d+\x2Fcommunicatortb
User-Agent\x3A\s+Host\x3A[^\n\r]*Hourspjpoptwql\x2frlnjFrom\x3Asbver\x3aGhost
User-Agent\x3A\s+community\d+
User-Agent\x3A\s+information\swww\x2Etopadwarereviews\x2Ecom
User-Agent\x3AreadyHost\x3AHost\x3ASubject\x3Awininetproducts
User-Agent\x3aUser-Agent\x3A
User-Agent\x3aUser-Agent\x3AReport\x2EHost\x3Afhfksjzsfu\x2fahm\.uqs
User-Agent\x3a\s+Host\x3A\s+Referer\x3a
User-Agent\x3a\s+Host\x3A\s+proxystylesheet=Excitefhfksjzsfu\x2fahm\.uqs
User-Agent\x3a\s+sErver\s+-~-GREATHost\x3a
User-Agent\x3awww\x2Eadoptim\x2Ecom
WinSession\w+asdbiz\x2Ebiz\dpjpoptwql\x2frlnj\x2Fpagead\x2Fads\?
X-Mailer\x3A\s+www\.iggsey\.com
X-Mailer\x3aUser-Agent\x3A
X-OSSproxy\x3a\w+\+Version\+\s+fast-look\x2Ecomwww\x2Emaxifiles\x2Ecom
XP\d+Acme\s+\x2Fcbn\x2Fnode=Host\x3A\x3Fsearch\x3DversionContact
YAHOODesktopHost\x3aLOGHost\x3AtvshowticketsResultsFROM\x3A
YOUR.*\x2Fsearchfast\x2F\s+hostiedesksearch\.dropspam\.com\x2Fbi\x2Fservlet\x2FThinstall
YWRtaW46YWRtaW4www\x2Ee-finder\x2EccNSIS_DOWNLOADHost\x3A
Yeah\!Host\x3AEnTrYwww\x2EZSearchResults\x2Ecom
ZC-Bridge\d+JMail\d+GENERAL_PARAM2
\.bmp[^\n\r]*couponbar\.coupons\.com.*Host\x3AHost\x3aHTTPwww
\.exe\s+ZC-Bridge\s+TPSystemHost\x3AHost\x3a
\.exe\s+v2\x2E0\s+smrtshpr-cs-
\.fcgi[^\n\r]*Host\x3A\s\x5D\x2520\x5BPort_NETObserveTM_SEARCH3
\stoolbar\.anwb\.nl.*Host\x3A
\stoolbar\.anwb\.nl\s+A-311\s+newsSoftActivitypassword\x3B1\x3BOptix
\swww\.fast-finder\.com[^\n\r]*\x2Fbar_pl\x2Fchk\.fcgi\d+Toolbar
\x0D\x0ACurrent\x2EearthlinkSpyBuddy
\x22Thewebsearch\.getmirar\.com
\x28\x29\s+WatchDog\sNetspy\d+pjpoptwql\x2frlnjX-Mailer\x3aHost\x3asnprtz\x7Cdialnoref\x3D\x25user\x5Fid
\x28robert\x40blackcastlesoft\x2Ecom\x29
\x2APORT2\x2Acdpnode=Host\x3A
\x2Ehtml\s+IDENTIFY\s+\x2Fbar_pl\x2Ffav\.fcgiwwwUser-Agent\x3A
\x2Ephp\s+www\x2Ewebfringe\x2Ecom
\x2FGR\s+\x2APORT3\x2A\d+Host\x3A
\x2Fbonzibuddy\x2Forigin\x3DsidefindApofisUser-Agent\x3A
\x2Fcs\x2Fpop4\x2FA-Spywww\x2Eyoogee\x2Ecom
\x2Fezsb\s+hirmvtg\x2fggqh\.kqh\dRemotetoolsbar\x2Ekuaiso\x2Ecom
\x2Fimages\x2Fnocache\x2Ftr\x2Fgca\x2Fm\.gif\?
\x2Frss\d+answer\sHost\x3A
\x2Fsearchfast\x2F\s+Host\x3A\s+
\x2Fta\x2FNEWS\x2Fpassword\x3B1\x3BOptix
\x3BCIA\s+is\s+User-Agent\x3Acid=tb\x2eCookie\x3A
\x7D\x7BPort\x3AHost\x3Amqnqgijmng\x2fojNavhelperUser-Agent\x3A
\x7D\x7BTrojan\x3A\w+Host\x3A\s\d\x2El
\x7D\x7BTrojan\x3A\w+by\d+to\w+dddlogin\x2Edudu\x2EcomSurveillanceIPOblivion
actualnames\.comclient\x2Ebaigoo\x2Ecomzzzvmkituktgr\x2fetiexpsp2-InformationHost\x3A
ad\x2Esearchsquire\x2Ecom\s+ocllceclbhs\x2fgth
adserver\.warezclient\.com\s+URLBlaze\s+Host\x3AHost\x3A
aohobygi\x2fzwiw\s+\+The\+password\+is\x3A
are\s+Toolbar\s+X-Mailer\x3AInformationsearchnuggetspastb\x2Efreeprod\x2Ecom
as\x2Estarware\x2Ecom%3fUser-Agent\x3Ahostie
attachedEverywareHELOBasic
awbeta\.net-nucleus\.com\d
bind\w+Owner\x3A\dBetaWordixqshv\x2fqzccs
body=\x2521\x2521\x2521Optix\s+Host\x3a
cid=tb\x2e\s+NETObserve\s+WinSession
client\x2Ebaigoo\x2EcomUser\x3A
clvompycem\x2fcen\.vcnHost\x3AUser-Agent\x3A\x0d\x0a
cojud\x2Edmcast\x2Ecom\sApofis\w+Referer\x3Awww\x2Emirarsearch\x2Ecom
comLOGUser-Agent\x3Aistsvcwww\x2Eoemji\x2EcomSystemSleuth
comUser-Agent\x3Asi=PORT\x3D\x2Fpagead\x2Fads\?Host\x3a\x2Fdesktop\x2F
com\dsearch\x2econduit\x2ecom\s+User-Agent\x3A
configINTERNAL\.ini\s+User-Agent\x3A\s+Host\x3ASubject\x3a
config\x2E180solutions\x2Ecom\dStable\s+Host\x3a\x7D\x7C
connectedNodes\s+insert\s+haveFTUser-Agent\x3A
corep\x2Edmcast\x2Ecom[^\n\r]*Referer\x3a.*is[^\n\r]*KeyloggerExplorerfileserverSI\|Server\|www\x2Emyarmory\x2Ecom
couponbar\.coupons\.com\dOwner\x3A\s+Host\x3A
daosearch\x2EcomSubject\x3A
data\.warezclient\.comHost\x3AUser-Agent\x3A
dialup\x5fvpn\x40hermangroup\x2Eorg\s+www\x2Epeer2mail\x2Ecom
dialupvpn\x5fpwd\d\<title\>Actual\sSpywareStrike\s+fowclxccdxn\x2fuxwn\.ddywww\x2evirusprotectpro\x2ecom
dll\x3F\w+updates\w+Host\x3aSoftwareHost\x3Ajoke
e2give\.com.*Login\s+adfsgecoiwnf\x23\x23\x23\x23User-Agent\x3A
ed2k\xc0STATUS\xc0Server\x7D\x7BPort\x3Ahttp\x3A\x2F\x2Ftv\x2Eseekmo\x2Ecom\x2Fshowme\x2Easpx\x3Fkeyword=
filename=\x22Subject\x3awww\x2Eadoptim\x2Ecomreport\x2Fbar_pl\x2Fchk\.fcgi
filename=\x22\s+www\x2Epeer2mail\x2Ecom.*LOG
forum=From\x3acomTencentTravelerBackAtTaCkExplorer
freeIPaddrsRunner\+The\+password\+is\x3A
from\s+\x2Fdss\x2Fcc\.2_0_0\.[^\n\r]*uploadServer
from\x3AUser-Agent\x3AChildWebGuardian
gpstool\x2eglobaladserver\x2ecom\daction\x2E\w+data2\.activshopper\.com
horoscope2YAHOOwww\x2e2-seek\x2ecom\x2fsearchHost\x3A
http\x3A\x2F\x2Ftv\x2Eseekmo\x2Ecom\x2Fshowme\x2Easpx\x3Fkeyword=
info\s+wjpropqmlpohj\x2flo\s+resultsmaster\x2Ecom\x7croogoo\x7c
is\s+lnzzlnbk\x2fpkrm\.fin\s+Host\x3A\x2Ftoolbar\x2Fsupremetb
isiz=Xtrastepwebhancer\x2EcomStubbyOnever\x3aGhost
ixqshv\x2fqzccsMM_RECO\x2EEXE%3fwwwwp-includes\x2Ftheme\x2Ephp\x3F
jsp\d+Host\x3A\d+moreKontikiHost\x3aAcmeEvilFTP
jsp\s+pjpoptwql\x2frlnj[^\n\r]*Host\x3A
kl\x2Esearch\x2Eneed2find\x2Ecom\ssource%3Dultrasearch136%26campaign%3Dsnap
logsFictionalReporterCookieUser-Agent\x3A
logs\s+TCP.*Toolbarads\.grokads\.com
mPOPUser-Agent\x3AgotS\x3aUsers\x5cPORT\x3DHXLogOnlyMGS-Internal-Web-Manager
mywayUser-Agent\x3AHost\x3ARedirector\x22body=FeaR\x25200\x2E2\x2E0\x2520Online\x3A\x2520\x5BIP_
name\x2ecnnic\x2ecn\scom\x2Findex\.php\?tpid=\s\x5BStatic.*\x2Fbar_pl\x2Fb\.fcgi
ovplSubject\x3ATencentTravelerClient\x7D\x7BSysuptime\x3A
pjpoptwql\x2frlnjsportsHost\x3ASubject\x3aYAHOOdestroyed\x21
requested\s+Reports\s+HostHost\x3aHost\x3AHost\x3AMyWebSearchSearchAssistant
s_sq=aolsnssigninUser-Agent\x3A
search\.dropspam\.com.*SupportFiles.*Referer\x3A
searchnugget\s+User-Agent\x3A\s+Downloadfowclxccdxn\x2fuxwn\.ddy
securityOmFkbWluADROARad\x2Emokead\x2Ecom\x3C\x2Fchat\x3E
sidesearch\.dropspam\.com\s+Strip-Player\s+
spas\s+This\s+\x7D\x7BPassword\x3A\s+OSSProxy\x5Chome\/lordofsearch
sql.*badurl\x2Egrandstreetinteractive\x2Ecom
stats\x2edrivecleaner\x2ecomExciteasdbiz\x2Ebiz
thesearchresltLoggerHost\x3ABetaHWAEHost\x3Ais
this\s+MyBrowser\d+Redirector\x22ServerHost\x3AX-Mailer\x3A
this\w+c\.goclick\.com\d
to=.*JMail\d+HXDownloadasdbiz\x2EbizUser-Agent\x3Awww\x2Eezula\x2Ecom
too[^\n\r]*User-Agent\x3A\sHost\x3A.*IP-WindowsAttachedPalas\x2Estarware\x2Ecom\x2Fdp\x2Fsearch\?x=
toolbarplace\x2Ecom.*Host\x3A\dgpstool\x2eglobaladserver\x2ecom
toolbarplace\x2Ecom.*TencentTraveler\d+\x2Fnewsurfer4\x2F.*BysooTBADdcww\x2Edmcast\x2Ecom
toolsbar\x2Ekuaiso\x2Ecom\d\x2Fbar_pl\x2Fchk_bar\.fcgi
tv\x2E180solutions\x2EcomGirlFriendHost\x3A
twfofrfzlugq\x2feve\.qd\d+
upgrade\x2Eqsrch\x2Einfo[^\n\r]*dcww\x2Edmcast\x2Ecom
url=\d+Host\x3A.*backtrust\x2Ecomv\x2ELoginHost\x3a\x2Ffriendship\x2Femail_thank_you\?
url=http\x3A\s+jsp\w+Subject\x3Ai\-femdom\x2EcomUser-Agent\x3A
uuid=\s+User-Agent\x3a\d+\x5Chome\/lordofsearch
vbwwwc\.goclick\.compassword\x3B0\x3BIncorrect
weatherSubject\x3aX-Mailer\x3aTOOLBAR\x2Fnewsurfer4\x2F
whenu\x2Ecom\d+Agent\stoWebupdate\.cgithisHost\x3aconnection
wjpropqmlpohj\x2flo\s+media\x2Edxcdirect\x2Ecom
wowokay\d+FTP\s+Host\x3AFiltered\x22reaction\x2Etxt\x22
www\.actualnames\.com\s+toolbar_domain_redirect\s+Contactfrom=GhostVoiceServer
www\.iggsey\.com\sX-Mailer\x3a[^\n\r]*on\x3Acom\x3E2\x2E41Client
www\.thecommunicator\.net\sHost\x3A\dhoroscope2
www\x2EZSearchResults\x2Ecom\dBar.*sponsor2\.ucmore\.com
www\x2Ecameup\x2Ecom\s+spyblini\x2Eini
www\x2Eemp3finder\x2Ecom\d+ZOMBIES\x5fHTTP\x5fGET
www\x2Efreescratchandwin\x2Ecom\w+Port.*User-Agent\x3AToolbarkit
www\x2Elookster\x2Enetnotificationuuid=qisezhin\x2fiqor\.ym
www\x2Emakemesearch\x2EcomLOGOnevclxatmlhavj\x2fvsy
www\x2Epurityscan\x2Ecom.*
www\x2Ericercadoppia\x2Ecom\w+TPSystem\s+User-Agent\x3A
www\x2Eserverlogic3\x2Ecom
www\x2Eserverlogic3\x2Ecom\d+ToolBar\s+HWAEUser-Agent\x3A
www\x2Ewebcruiser\x2Eccgot
www\x2Eweepee\x2Ecom\w+Owner\x3A\d+metaresults\.copernic\.com
www\x2eurlblaze\x2enetCurrentHost\x3A
xmlHost\x3ADAPCURLBlazeActivity
xpsp2-\s+spyblpat.*is\x2EphpBarFrom\x3A
zopabora\x2Einfo\s+Inside\s+SystemSleuth\s+www\x2Eyok\x2EcomHost\x3AInformationwww\x2Ezhongsou\x2EcomLite
