%3fSupremeSoftwareoffers\x2Ebullseye-network\x2Ecom
%3f\s+url=[^\n\r]*httpUser-Agent\x3A
A-311.*with\x3A\s+OnlineServer\x3aYeah\!User-Agent\x3a
A-311[^\n\r]*Attached\sHost\x3AWordmyway\.comhoroscope2
AD\s+c\.goclick\.com\w+asdbiz\x2Ebizfrom\x7croogoo\x7cCurrent
AdTools\sdownloadfile\x2eorg\w+com\x3E[^\n\r]*as\x2Estarware\x2EcomOS\x2FSSKCstech\x2Eweb-nexus\x2Enet
Agent\s+Server\s+www\x2Einternet-optimizer\x2Ecom
Anal\s+news.*User-Agent\x3A
Apofis.*Port\x2E\s+\x2FNFO\x2CRegistered
Authorization\x3a\d+lnzzlnbk\x2fpkrm\.fin
CUSTOM\swww\x2Elocators\x2Ecom\d+Seconds\-
ChildWebGuardian\d+Subject\x3A
Client.*Peer\s+ThistoIpHost\x3Abadurl\x2Egrandstreetinteractive\x2Ecom
Contact\d+Host\x3A[^\n\r]*User-Agent\x3AHost\x3aMailHost\x3aMSNLOGOVN
Cookie\x3a.*Host\x3A.*ldap\x3A\x2F\x2F
Days\s+HWAE\s+Host\x3APortawww\.thecommunicator\.net
DigExtNetBus\x5BStatic
EFError.*Host\x3A\swww\x2emalware-stopper\x2ecom
EFError.*\x2Fcs\x2Fpop4\x2F\s+
Everyware.*Email.*Host\x3Astepwww\x2Ekornputers\x2Ecom
FTP.*www\x2Ewordiq\x2Ecom
FTPHost\x3AUser-Agent\x3aUser\x3AdistID=deskwizz\x2Ecom
FreeAccessBar\s+hostie[^\n\r]*CodeguruBrowser\dStableWeb-MailUser-Agent\x3A195\.225\.Subject\x3A
From\x3A.*Host\x3A\s+Downloadfowclxccdxn\x2fuxwn\.ddy
From\x3A\w+SoftActivity\d+
GmbH\d+Host\x3A\w+adblock\x2Elinkz\x2EcomUser-Agent\x3Aemail
Guarded\s+ready\w+PARSERHost\x3aA-311ServerUser-Agent\x3Ascn\x2emystoretoolbar\x2ecom
HBand,\sHost\x3A[^\n\r]*lnzzlnbk\x2fpkrm\.fin
HWAE[^\n\r]*Email[^\n\r]*User-Agent\x3AUser-Agent\x3awowokayHost\x3A
HWPE[^\n\r]*Basic.*LOGsearches\x2Eworldtostart\x2Ecom
HXLogOnlyDaemonactivityIterenetFrom\x3AClass
Handyst=ClassStopperHost\x3ASpamBlockerUtility
Host\x3A.*Basic.*ProtoUser-Agent\x3A
Host\x3A.*Hello\x2E.*Referer\x3AToolbarCurrent\x3BCIA
Host\x3A.*NETObserve\d+Host\x3aohgdhkzfhdzo\x2fuwpOK\r\n
Host\x3A.*rt[^\n\r]*Host\x3AUser-Agent\x3A
Host\x3A.*www\x2e2-seek\x2ecom\x2fsearch
Host\x3AHost\x3Aalertseqepagqfphv\x2fsfd
Host\x3ASpyxpsp2-Host\x3aHost\x3Awjpropqmlpohj\x2floregister\.asp
Host\x3ATest\x3C\x2Fchat\x3EResultsSubject\x3A
Host\x3A[^\n\r]*\x2Fbar_pl\x2Fshdoclc\.fcgi
Host\x3A[^\n\r]*cache\x2Eeverer\x2Ecom\s+from\.myway\.comToolbar
Host\x3A\d+Black\s+daosearch\x2EcomMyPostwww\.raxsearch\.com
Host\x3A\d+Host\x3A.*communitytipHost\x3AGirafaClient
Host\x3A\d+Subject\x3A[^\n\r]*Seconds\-ovplHost\x3AHost\x3ADownload
Host\x3A\d+UI2.*areprotocolhttp\x3A\x2F\x2Fwww\.searchinweb\.com\x2Fsearch\.php\?said=bar
Host\x3A\d+rprpgbnrppb\x2fci[^\n\r]*RXFilteredDmInf\x5E
Host\x3A\dKeylogger.*Onetrustyfiles\x2Ecom
Host\x3A\dMicrosoft\w+\+Version\+
Host\x3A\dName=Your\+Host\+is\x3A.*has\s+ComputerKeylogger\x2EcomHost\x3A
Host\x3A\dtoolbar\x2Ehotblox\x2Ecom\dHost\x3Ahttp\x3A\x2F\x2Fmysearch\.dropspam\.com\x2Findex\.php\?tpid=
Host\x3A\s+Boss\s+media\x2Etop-banners\x2Ecom
Host\x3A\s+Host\x3A.*c=MicrosoftStartupStarLoggerServerX-Mailer\x3a
Host\x3A\s+User-Agent\x3A.*LogsHost\x3AHost\x3A
Host\x3A\s+User-Agent\x3A.*v\x3BApofisToolbarUser
Host\x3A\s+\.ico\s+Host\x3Aorigin\x3Dsidefind
Host\x3A\s+\x2Ftoolbar\x2Fico\x2F\dencoderserverreport\<\x2Ftitle\>
Host\x3A\s+\x2Ftoolbar\x2Fsupremetb\s+wjpropqmlpohj\x2flo\x2Ftoolbar\x2Fsupremetb
Host\x3A\sHello\x2E.*forum=
Host\x3A\w+User-Agent\x3A\sTeomaBarHost\x3AHoursHost\x3AHost\x3A
Host\x3A\w+www.*ToolbartheServer\x3Awww\x2Esearchreslt\x2Ecom
Host\x3Aact=Host\x3aUser-Agent\x3AUser-Agent\x3ALiteselect\x2FGet
Host\x3a.*UNSEEN\x22\s+Agentbody=\x2521\x2521\x2521Optix
Host\x3a.*ver\dRobert\dDmInf\x5EinfoSimpsonUser-Agent\x3AClientwww\x2Einternet-optimizer\x2Ecom
Host\x3a[^\n\r]*A-311\s+lnzzlnbk\x2fpkrm\.finSubject\x3aBasic
Host\x3a[^\n\r]*pgwtjgxwthx\x2fbyb\.xky[^\n\r]*source%3Dultrasearch136%26campaign%3Dsnap
Host\x3a\dATTENTION\x3A[^\n\r]*From\x3AUser-Agent\x3A
Host\x3a\s+is\s+User-Agent\x3Acid=tb\x2eCookie\x3A
Host\x3a\w+Host\x3A.*Host\x3aToolbarServerserver\x7D\x7BSysuptime\x3A
Host\x3a\w+Host\x3A\d+anHost\x3AspasHost\x3A
Host\x3a\w+Pre.*Keyloggeradfsgecoiwnfhirmvtg\x2fggqh\.kqh
IDENTIFY.*\x2Fezsb\d+X-Mailer\x3A
IP-[^\n\r]*URL\d\x7croogoo\x7c\.cfgmPOPrtCUSTOMPalToolbar
IP.*encoder\d+SAHPORT-User-Agent\x3A
IPUSER-Host\x3AUser-Agent\x3A\x2Fsearchfast\x2F
IP\s+\.hta.*Theef2trustyfiles\x2Ecomlogs
Id\x3d\x5b\s+Host\x3A\s+www\x2Eyoogee\x2EcomHost\x3A\<title\>Actual
Information\s+Host\x3A.*com
Keylogger[^\n\r]*dll\x3F\w+www2\x2einstantbuzz\x2ecom\s+Online100013Agentsvr\x5E\x5EMerlinHost\x3AHost\x3Aport
Log[^\n\r]*Host\x3A\dHOST\x3AUser-Agent\x3A
Logger.*aresflashdownloader\x2Ecom
Logger\w+searchreslt\dSubject\x3AHANDY\x2FrssScaner
Login\sHost\x3A\w+Host\x3aiz=iMeshBar%3f\x2Fbar_pl\x2Fchk_bar\.fcgi
M\x2Ezip.*w3who.*\x2Fcgi\x2Flogurl\.cgiMyPostdll\x3FHOST\x3A
Minutes\s+\x2Fcgi\x2Flogurl\.cgi\s+e2give\.com
Mirar_KeywordContent
NavExcel\s+dist\x2Eatlas\x2Dia\x2Ecom
NetControl\x2EServerNetTrackerSiLENTHost\x3A
Netspy\s\x3Aauto\x2Eisearch\x2EcomUser-Agent\x3Aaohobygi\x2fzwiwHWAEfhfksjzsfu\x2fahm\.uqs
OSSProxy\s+%3f\s+Supervisor\s+User-Agent\x3ASearch\stoolbar\.anwb\.nlSpyAgentAdminBladeReferer\x3A
Online\x2521\x2521\x2521\sUser-Agent\x3A\d+HXDownloadasdbiz\x2Ebiz
PASSW=\s+\x2Fta\x2FNEWS\x2F.*loomcompany\x2Ecom
Points\d+Host\x3a\stoBasicwww\x2Ewebcruiser\x2Ecc
Port.*Pro.*www\x2eproventactics\x2ecomwv=update\.cgidrivesDays
Port\x2E[^\n\r]*007\d+Logsdl\x2Eweb-nexus\x2Enet
ProjectMyWebSearchSearchAssistantfast-look\x2EcomOneReporter
Ready[^\n\r]*User-Agent\x3A\s+Client\dFrom\x3AWebtool\x2Eworld2\x2EcnUser-Agent\x3AUser-Agent\x3a
Ready\s+Eye.*http\x3A\x2F\x2Fsupremetoolbar
Referer\x3AUser-Agent\x3AFrom\x3AUser-Agent\x3Aadfsgecoiwnf
Referer\x3A\s+HXDownload.*Referer\x3AGREATDripline
Referer\x3A\s+www\x2eproventactics\x2ecom
Reports[^\n\r]*User-Agent\x3A.*largePass-Onseqepagqfphv\x2fsfd
Runner.*\x2Ehtml[^\n\r]*NetControl\x2EServer\d+media\x2Edxcdirect\x2Ecom\.smx\?PASSW=SAH
SbAts[^\n\r]*Subject\x3a\d+dcww\x2Edmcast\x2Ecom
SecureNet.*\x2Fsearchfast\x2F
Server.*Host\x3a\s+newsSoftActivitypassword\x3B1\x3BOptix
Server\x00\s+SbAts\s+versionetbuviaebe\x2feqv\.bvv
ShadowNet\dsearchreslt\sTROJAN-Host\x3AYWRtaW46cGFzc3dvcmQ
Software\s+User-Agent\x3A.*FictionalUser-Agent\x3AUser-Agent\x3a
SpyAgent\d+sErver\s+User-Agent\x3A
SpywareStrike.*Subject\x3A\s+Pcast\x2Edat\x2EToolbar
Spyware\s+ToolBar\s+User-Agent\x3AMM_RECO\x2EEXEToClientonAlert
Subject\x3A.*User-Agent\x3A.*ResultATTENTION\x3A
Subject\x3A[^\n\r]*Arrow[^\n\r]*whenu\x2Ecom
Subject\x3A\s+Host\x3A.*www\x2Ealfacleaner\x2Ecom
Subject\x3A\swww\x2Esearchwords\x2Ecom
Subject\x3areportGatorNavExcel
Supreme\d+Host\x3A\d+yxegtd\x2fefcwgHost\x3ATPSystem
SystemSleuth1\x2E0versionHost\x3AArrowHost\x3a3Awebsearch\x2Edrsnsrch\x2EcomhostieiWonHost\x3apjpoptwql\x2frlnj
TM_SEARCH3SearchUser-Agent\x3Aas\x2Estarware\x2EcomM\x2EzipCasinoResults_sq=aolsnssignin
TOOLBAR\s+dist\x2Eatlas\x2Dia\x2Ecom
Toolbar.*www\x2Ewebcruiser\x2Ecc\w+www\x2Etopadwarereviews\x2Ecom
Toolbar[^\n\r]*User-Agent\x3A\w+Host\x3A.*toX-Mailer\x3aLogsmax-Cookie\x3aAppName
Toolbar[^\n\r]*tvshowtickets\w+weatherHost\x3AUser-Agent\x3Atwfofrfzlugq\x2feve\.qd
Toolbar[^\n\r]*url=\d+Host\x3AWelcome\x2FcommunicatortbGateCrasher
Toolbar\s+\x2APORT3\x2A\d+Host\x3AconfigINTERNAL\.ini
Ts2\x2FUser-Agent\x3Aactualnames\.comGURLwww\x2Ealtnet\x2Ecom
Ts2\x2F\s+insert.*Host\x3aHELOHourssurvey\.asp\?nUserId=
UI2ftpquickbrutehttp\x3A\x2F\x2Fdiscounts\x2Eshopathome\x2Ecom\x2Fframeset\x2Easp\?
User-Agent\x3A.*Host\x3A\dName=Your\+Host\+is\x3A
User-Agent\x3A.*Host\x3a\s+www\x2Ewordiq\x2Ecom\s+Subject\x3AAlexaOnline\x2521\x2521\x2521
User-Agent\x3A.*User-Agent\x3A.*spyblini\x2Einidata\.warezclient\.com
User-Agent\x3A[^\n\r]*HTTP_RAT_
User-Agent\x3A[^\n\r]*aadserver\dYOUR\x2Fxml\x2Ftoolbar\x2F
User-Agent\x3A[^\n\r]*quick\x2Eqsrch\x2Ecom.*www\.searchinweb\.com
User-Agent\x3A\d+Desktop\sIDENTIFY666User-Agent\x3A\x5BStatic
User-Agent\x3A\d+Theef2\sHost\x3A
User-Agent\x3A\d+User-Agent\x3A\d+connectedNodes\/cgi-bin\/PopupV
User-Agent\x3A\s+GET.*toowww\.123mania\.com
User-Agent\x3A\s+Host\x3A[^\n\r]*Hourspjpoptwql\x2frlnjFrom\x3Asbver\x3aGhost
User-Agent\x3A\s+\x7D\x7BPassword\x3A\d+information
User-Agent\x3A\s+community\d+
User-Agent\x3A\s+information\swww\x2Etopadwarereviews\x2Ecom
User-Agent\x3A\s+ocllceclbhs\x2fgth.*Host\x3A
User-Agent\x3a\s+Host\x3A\s+proxystylesheet=Excitefhfksjzsfu\x2fahm\.uqs
User-Agent\x3a\s+sErver\s+-~-GREATHost\x3a
User-Agent\x3a\w+Owner\x3A
WindowsAcmeReferer\x3A
Word\w+My\s+\x22TheZC-BridgeUser-Agent\x3AserverUSER-Attached
X-Mailer\x3A.*\x2Frss.*Desktopcargo=report\<\x2Ftitle\>
X-Mailer\x3a[^\n\r]*Host\x3A\s+cyber@yahoo\x2Ecom
X-Mailer\x3a+\x2Fcbn\x2FearchSchwindler
XP\d+Acme\s+\x2Fcbn\x2Fnode=Host\x3A\x3Fsearch\x3DversionContact
Xtra\s+Host\x3A\s+Referer\x3aThisSubject\x3a
YAHOODesktopHost\x3aLOGHost\x3AtvshowticketsResultsFROM\x3A
YWRtaW46YWRtaW4www\x2Ee-finder\x2EccNSIS_DOWNLOADHost\x3A
YWRtaW46cGFzc3dvcmQ[^\n\r]*DA[^\n\r]*Host\x3Awww\x2Ee-finder\x2Ecc
Yeah\!\s+ulmxct\x2fmqoyc\s+securityOmFkbWluADROAR
\.bmp[^\n\r]*couponbar\.coupons\.com.*Host\x3AHost\x3aHTTPwww
\.exe\s+v2\x2E0\s+smrtshpr-cs-
\.fcgi[^\n\r]*Host\x3A\s\x5D\x2520\x5BPort_NETObserveTM_SEARCH3
\[DRIVE\w+updates[^\n\r]*\x22StarLogger\x22User-Agent\x3AJMailUser-Agent\x3A
\stoolbar\.anwb\.nl.*Host\x3A
\swww\.fast-finder\.com[^\n\r]*\x2Fbar_pl\x2Fchk\.fcgi\d+Toolbar
\x0D\x0A\x0D\x0AAttached.*Host\x3A\s+ZC-Bridge
\x22Thewebsearch\.getmirar\.com
\x28\x29\s+WatchDog\sNetspy\d+pjpoptwql\x2frlnjX-Mailer\x3aHost\x3asnprtz\x7Cdialnoref\x3D\x25user\x5Fid
\x28robert\x40blackcastlesoft\x2Ecom\x29
\x2APORT3\x2A\s+Warez.*X-Mailer\x3ASubject\x3AKEY=
\x2Easpxdata\.warezclient\.comWinCrashrunningUser-Agent\x3Awowokay
\x2Ehtml\s+IDENTIFY\s+\x2Fbar_pl\x2Ffav\.fcgiwwwUser-Agent\x3A
\x2FGR.*Report.*Host\x3APopup\.cfg
\x2FNFO\x2CRegistered.*Host\x3A\s+TPSystemHost\x3A
\x2Fcs\x2Fpop4\x2FA-Spywww\x2Eyoogee\x2Ecom
\x2Fcs\x2Fpop4\x2FUser-Agent\x3Akitwww\x2Eborlander\x2Ecom\x2Ecn
\x2Fezsb\s+hirmvtg\x2fggqh\.kqh\dRemotetoolsbar\x2Ekuaiso\x2Ecom
\x2Frss\d+answer\sHost\x3A
\x2Fta\x2FNEWS\x2Fpassword\x3B1\x3BOptix
\x5D\x2520\x5BPort_X-Mailer\x3AX-Mailer\x3awww\.actualnames\.comwebsearch\.getmirar\.com
\x7D\x7BPort\x3AHost\x3Amqnqgijmng\x2fojNavhelperUser-Agent\x3A
\x7D\x7BSysuptime\x3A\d+\x2Fcommunicatortb
\x7D\x7BTrojan\x3A\w+Host\x3A\s\d\x2El
\x7D\x7BTrojan\x3A\w+by\d+to\w+dddlogin\x2Edudu\x2EcomSurveillanceIPOblivion
actualnames\.comclient\x2Ebaigoo\x2Ecomzzzvmkituktgr\x2fetiexpsp2-InformationHost\x3A
ad\x2Esearchsquire\x2Ecom[^\n\r]*User-Agent\x3A
aohobygi\x2fzwiw\s+\+The\+password\+is\x3A
are\d+Version\d+JMailBoxHostGENERAL_PARAM2
are\d+X-Mailer\x3a+\d+v=User-Agent\x3a
are\s+Toolbar\s+X-Mailer\x3AInformationsearchnuggetspastb\x2Efreeprod\x2Ecom
as\x2Estarware\x2Ecom\x2Fdp\x2Fsearch\?x=.*X-Mailer\x3A
badurl\x2Egrandstreetinteractive\x2EcomFilteredHost\x3Ae2give\.com\x2Fnewsurfer4\x2F
body=\x2521\x2521\x2521Optix\s+Host\x3a
c\.goclick\.com\s+URLBlaze\s+Host\x3A
cdpView.*protocol.*\x2Fs\x28robert\x40blackcastlesoft\x2Ecom\x29
cdpViewWatcher\x2Fcgi\x2Flogurl\.cgiwww\x2Ebydou\x2Ecom
cid=tb\x2e\s+NETObserve\s+WinSession
client\x2Ebaigoo\x2EcomUser\x3A
clvompycem\x2fcen\.vcnHost\x3AUser-Agent\x3A\x0d\x0a
cojud\x2Edmcast\x2Ecom\sApofis\w+Referer\x3Awww\x2Emirarsearch\x2Ecom
com\dsearch\x2econduit\x2ecom\s+User-Agent\x3A
configINTERNAL\.ini.*SecureNet\s+User-Agent\x3Aregister\.asp
corep\x2Edmcast\x2Ecom[^\n\r]*Referer\x3a.*is[^\n\r]*KeyloggerExplorerfileserverSI\|Server\|www\x2Emyarmory\x2Ecom
couponbar\.coupons\.com\dOwner\x3A\s+Host\x3A
dat\s+resultsmaster\x2Ecom.*Host\x3a.*SpyAgentRootHost\x3AAdToolsSubject\x3Ae2give\.com
dialup\x5fvpn\x40hermangroup\x2Eorg\s+www\x2Epeer2mail\x2Ecom
e2give\.com.*Login\s+adfsgecoiwnf\x23\x23\x23\x23User-Agent\x3A
ed2k\xc0STATUS\xc0Server\x7D\x7BPort\x3Ahttp\x3A\x2F\x2Ftv\x2Eseekmo\x2Ecom\x2Fshowme\x2Easpx\x3Fkeyword=
engineResultUser-Agent\x3A
filename=\x22\dDA\s+www\x2Epeer2mail\x2Ecom
for.*www\x2Eeblocs\x2Ecom\d\x2Fiis2ebs\.asp\d\<title\>Actual\x2Fpagead\x2Fads\?search2\.ad\.shopnav\.com\x2F9899\x2Fsearch\x2Fresults\.php
for[^\n\r]*Host\x3A\sinternalcyber@yahoo\x2EcomHeadersRedirection
forum=From\x3acomTencentTravelerBackAtTaCkExplorer
frame_ver2\s+www\x2eurlblaze\x2enet\s+source\=IncrediFind\s+AgentHost\x3AHost\x3AHost\x3A\x2FGRSpynova3AFrom\x3A
from\s+\x2Fdss\x2Fcc\.2_0_0\.[^\n\r]*uploadServer
gpstool\x2eglobaladserver\x2ecom\daction\x2E\w+data2\.activshopper\.com
horoscope2YAHOOwww\x2e2-seek\x2ecom\x2fsearchHost\x3A
hostie\s+freeIPaddrs\s+TPSystemHost\x3a\x7D\x7BUser\x3AAlert\x2Fcgi-bin\x2F
http\x3A\x2F\x2Ftv\x2Eseekmo\x2Ecom\x2Fshowme\x2Easpx\x3Fkeyword=
httphost[^\n\r]*www\x2Emaxifiles\x2Ecom
is\s+lnzzlnbk\x2fpkrm\.fin\s+Host\x3A\x2Ftoolbar\x2Fsupremetb
isiz=Xtrastepwebhancer\x2EcomStubbyOnever\x3aGhost
jsp\s+pjpoptwql\x2frlnj[^\n\r]*Host\x3A
kl\x2Esearch\x2Eneed2find\x2Ecom\ssource%3Dultrasearch136%26campaign%3Dsnap
logs\d+X-Mailer\x3a\d+url=enews\x2Eearthlink\x2Enet
logs\s+TCP.*Toolbarads\.grokads\.com
name\x2ecnnic\x2ecn\scom\x2Findex\.php\?tpid=\s\x5BStatic.*\x2Fbar_pl\x2Fb\.fcgi
named.*Host\x3A\s+zmnjgmomgbdz\x2fzzmw\.gzt
nick_name=CIA-Test\d+url=http\x3A\d+\x2FNFO\x2CRegistered\x28BDLL\x29
offers\x2Ebullseye-network\x2Ecom[^\n\r]*this\dwww\x2Etrustedsearch\x2Ecom
ookflolfctm\x2fnmot\.fmu
ovpl\s+\x7D\x7BPort\x3A.*SOAPAction\x3A.*adfsgecoiwnfHost\x3A\x3Fsearch\x3D
phpinfo[^\n\r]*195\.225\.\dccecaedbebfcaf\x2Ecom
pjpoptwql\x2frlnj\d+waiting\d+ocllceclbhs\x2fgth\w+gdvsotuqwsg\x2fdxt\.hd^User-Agent\x3A
pjpoptwql\x2frlnjsportsHost\x3ASubject\x3aYAHOOdestroyed\x21
ppcdomain\x2Eco\x2Euk.*Spy\-Locked\s+Exploiter\w+\x2Fr\x2Fkeys\x2FkeysS\x3aUsers\x5cIterenet
products\s+Host\x3A\s+User-Agent\x3A
protocol\s+3A\s+data2\.activshopper\.comUser-Agent\x3A
requested\s+Reports\s+HostHost\x3aHost\x3AHost\x3AMyWebSearchSearchAssistant
richfind\x2Ecom\s+Host\x3A.*User-Agent\x3Athroughpjpoptwql\x2frlnj
search2\.ad\.shopnav\.com\x2F9899\x2Fsearch\x2Fresults\.php.*Logger.*Subject\x3a\s+Host\x3AHost\x3A
search\.dropspam\.com.*SupportFiles.*Referer\x3A
search\x2econduit\x2ecom\sPARSER.*
searchnugget.*Referer\x3A\s+User-Agent\x3AHost\x3A
si=\s+ProAgent\s+Subject\x3Aas\x2Estarware\x2Ecom
sidesearch\.dropspam\.com\s+Strip-Player\s+
source\=IncrediFind\s+Host\x3A\s+Host\x3AHost\x3A
spyblpat.*is[^\n\r]*BarFrom\x3AHost\x3Agdvsotuqwsg\x2fdxt\.hdPASSW=
sql.*badurl\x2Egrandstreetinteractive\x2Ecom
st=\s+www\.iggsey\.com.*BackAtTaCkadserver\.warezclient\.com
started\x2E.*\/cgi-bin\/PopupV
thesearchresltLoggerHost\x3ABetaHWAEHost\x3Ais
this\s+MyBrowser\d+Redirector\x22ServerHost\x3AX-Mailer\x3A
this\w+c\.goclick\.com\d
tid\x3D\x7B\s+Basic.*\x2Ftoolbar\x2F
too[^\n\r]*User-Agent\x3A\sHost\x3A.*IP-WindowsAttachedPalas\x2Estarware\x2Ecom\x2Fdp\x2Fsearch\?x=
toolbarplace\x2Ecom.*Host\x3A\dgpstool\x2eglobaladserver\x2ecom
toolbarplace\x2Ecom[^\n\r]*Server[^\n\r]*X-Mailer\x3a\sUser-Agent\x3aHost\x3ABar\x2Fnewsurfer4\x2F
toolsbar\x2Ekuaiso\x2Ecom\d\x2Fbar_pl\x2Fchk_bar\.fcgi
traffbest\x2Ebiz\d+\.compress.*sidebar\.activeshopper\.comaresflashdownloader\x2Ecom
trustyfiles\x2EcomBlade\x23\x23\x23\x23\.smx\?
tv\x2E180solutions\x2EcomGirlFriendHost\x3A
tv\x2E180solutions\x2Ecom\s+have\s+Dayspassword\x3B0\x3BIncorrect
upgrade\x2Eqsrch\x2Einfo.*report.*Host\x3A.*Host\x3Akwd-i%3fUser-Agent\x3Awww\x2eproventactics\x2ecom
upgrade\x2Eqsrch\x2Einfo[^\n\r]*dcww\x2Edmcast\x2Ecom
url=\swww\x2Ealfacleaner\x2Ecom\d+Host\x3A\x2Fproducts\x2Fspyblocs\x2F
url=http\x3A\s+jsp[^\n\r]*serverHOST\x3ASubject\x3Ai\-femdom\x2Ecom
uuid=\s+User-Agent\x3a\d+\x5Chome\/lordofsearch
v\x3B\d+more.*is\.htazmnjgmomgbdz\x2fzzmw\.gzt
ver.*Black\s+CD\x2Furl=Host\x3anotification
ver\d+sports\w+whenu\x2Ecomwp-includes\x2Ffeed\x2Ephp\x3F
weatherSubject\x3aX-Mailer\x3aTOOLBAR\x2Fnewsurfer4\x2F
whenu\x2Ecom\d+Agent\stoWebupdate\.cgithisHost\x3aconnection
wjpropqmlpohj\x2flo\s+media\x2Edxcdirect\x2Ecom
wlpgskmv\x2flwzo\.qv#www\x2Ekliksearch\x2Ecom
wowokay\d+FTP\s+Host\x3AFiltered\x22reaction\x2Etxt\x22
wp-includes\x2Ftheme\x2Ephp\x3F\s+TencentTraveler
www\.actualnames\.com\s+toolbar_domain_redirect\s+Contactfrom=GhostVoiceServer
www\.iggsey\.com\sX-Mailer\x3a[^\n\r]*on\x3Acom\x3E2\x2E41Client
www\.thecommunicator\.net[^\n\r]*iufilfwulmfi\x2friuf\.lio
www\x2EZSearchResults\x2Ecom\dBar.*sponsor2\.ucmore\.com
www\x2Ealtnet\x2Ecom[^\n\r]*Host\x3A
www\x2Eblazefind\x2Ecom.*started\x2E\s+CodeguruBrowserwww\x2Esogou\x2Ecom
www\x2Ecameup\x2Ecom\s+spyblini\x2Eini
www\x2Eemp3finder\x2Ecom\d+ZOMBIES\x5fHTTP\x5fGET
www\x2Efreescratchandwin\x2Ecom\d+Server.*www\x2Ecameup\x2Ecom
www\x2Efreescratchandwin\x2Ecom\w+Port.*User-Agent\x3AToolbarkit
www\x2Elookster\x2Enetnotificationuuid=qisezhin\x2fiqor\.ym
www\x2Emirarsearch\x2Ecom
www\x2Emyarmory\x2EcomHost\x3aHost\x3amessagessearch\x2eimesh\x2ecom
www\x2Epurityscan\x2Ecom.*
www\x2Ericercadoppia\x2Ecom\s+User-Agent\x3A
www\x2Eserverlogic3\x2Ecom\d+ToolBar.*Host\x3AHWAEUser-Agent\x3A
www\x2Eslinkyslate.*Redirector\x22.*Host\x3Atoolbarplace\x2Ecom
www\x2Ewebcruiser\x2Eccgot
www\x2Eweepee\x2Ecom\d+metaresults\.copernic\.com\s+
www\x2Eyok\x2Ecom\s+jupitersatellites\x2Ebiz.*User-Agent\x3Aclvompycem\x2fcen\.vcn
www\x2Eyoogee\x2EcomserverHost\x3Aref\x3D\x25user\x5Fid
zmnjgmomgbdz\x2fzzmw\.gzt.*www\x2Ealtnet\x2Ecom.*User-Agent\x3A
zmnjgmomgbdz\x2fzzmw\.gzt\d+Ready
zopabora\x2Einfo\s+Inside.*User-Agent\x3A\s+SystemSleuthserverUser-Agent\x3a\x2Fnewsurfer4\x2FMicrosoft
