3A\s+URLBlazeHost\x3Atrackhjhgquqssq\x2fpjm
A-311\s+lnzzlnbk\x2fpkrm\.finSubject\x3aBasic
ATL\w+SoftActivitypassword\x3B0\x3BIncorrect
AdTools\d+rprpgbnrppb\x2fciExplorer\x2Fsto=notificationfindwww\x2Emakemesearch\x2Ecom
Address\x3A\s+SbAtsHTTP_RAT_Subject\x3A
Authorization\x3a\d+lnzzlnbk\x2fpkrm\.fin
Box\d+GENERAL_PARAM2FTA-SpyLoggerHost\x3A\.exePass-On
CUSTOM\swww\x2Elocators\x2Ecomas\x2Estarware\x2Ecom
Center\w+Host\x3aiz=iMeshBar
Client\d+Subject\x3AisBysooTBwhenu\x2EcomToolbar
Cookie\x3a\s+\x2FGRSI\|Server\|Host\x3Aorigin\x3Dsidefind
DISK\s+\x2Fcgi\x2Flogurl\.cgiSubject\x3AinsertX-Mailer\x3A
DmInf\x5E\s+Contactfrom=GhostVoiceServerUser-Agent\x3A
DmInf\x5E\s+offers\x2Ebullseye-network\x2Ecomlogfile
Dripline\d+X-Mailer\x3a\x04\x00TCP
EFError\swww\x2emalware-stopper\x2ecom
Fictional\sHost\x3AWordmyway\.com
Filtered\s+Yeah\!\d+HXDownloadasdbiz\x2EbizUser-Agent\x3Awww\x2Eezula\x2EcomUser-Agent\x3aetbuviaebe\x2feqv\.bvv
GmbH\s+Host\x3AHost\x3AMonitoringGoogle
Google\s+-~-GREATHost\x3aFILESIZE\x3E
HANDY\s+newsSoftActivitypassword\x3B1\x3BOptixtv\x2E180solutions\x2Ecom
HWAE\s+\x2Fta\x2FNEWS\x2FGuptacharloomcompany\x2Ecom
HXDownload\s+Host\x3AArcadeHourspjpoptwql\x2frlnjFrom\x3A
HXLogOnlyDaemonactivityIterenetFrom\x3AClass
HXLogOnly\w+Host\x3AspasHost\x3A
Handyst=ClassStopperHost\x3ASpamBlockerUtility
Hello\x2E\s+ovplrichfind\x2EcomCookie\x3a
Host\s+pjpoptwql\x2frlnjSubject\x3A
Host\x3AHost\x3Aalertseqepagqfphv\x2fsfd
Host\x3ATest\x3C\x2Fchat\x3EResultsSubject\x3A
Host\x3A\d+Litequick\x2Eqsrch\x2EcomaboutHost\x3AComputer\x7D\x7BSysuptime\x3A
Host\x3A\d+Subject\x3Aas\x2Estarware\x2Ecom\x2Fdp\x2Fsearch\?x=
Host\x3A\d+\x2Fcommunicatortb\swww\.fast-finder\.comBrowser\x2FGR
Host\x3A\d+zmnjgmomgbdz\x2fzzmw\.gzt%3ftoolbar\x2Ei-lookup\x2Ecom
Host\x3A\dKeyloggercargo=
Host\x3A\dwww\x2Etrustedsearch\x2Ecom
Host\x3A\s+A-311Servert=form-data\x3B\x20name=\x22pid\x22
Host\x3A\s+CD\x2F\s+twfofrfzlugq\x2feve\.qdSeconds\-\x2Ftoolbar\x2Fsupremetb
Host\x3A\s+Eyewww\x2Eccnnlc\x2EcomHost\x3aHost\x3a
Host\x3A\s+Host\x3ASubject\x3anamedDownloadUser-Agent\x3aBackAtTaCk
Host\x3A\s+Host\x3A\x7croogoo\x7cTestiufilfwulmfi\x2friuf\.lio
Host\x3A\s+Server\x00User-Agent\x3atoolsbar\x2Ekuaiso\x2Ecom
Host\x3A\s+Subject\x3aHost\x3A
Host\x3A\s+User-Agent\x3A
Host\x3A\s+User-Agent\x3A\s+ApofisToolbarUserhRatasdbiz\x2Ebizwww\x2Eserverlogic3\x2Ecom
Host\x3A\s+\.ico\x2FsLogearch195\.225\.Referer\x3A
Host\x3A\s+\x2FNFO\x2CRegisteredDeletingadfsgecoiwnf
Host\x3A\s+gpstool\x2eglobaladserver\x2ecomfriend_nickname=CIA-Notify-Tezt
Host\x3A\s+jspIDENTIFYserverHOST\x3A
Host\x3A\s+ulmxct\x2fmqoycWinSession\x2Fclient\x2F\x2APORT1\x2A
Host\x3A\s+www\x2Einternet-optimizer\x2EcomToolBarKeylogger
Host\x3A\s+www\x2Ewebfringe\x2Ecom\d+Version\d\x2ElSpywww\x2Elookquick\x2EcomSubject\x3A\x3a\x29\r\n
Host\x3A\s+www\x2Eyoogee\x2Ecom
Host\x3A\sToolbarServerserver\x7D\x7BSysuptime\x3A
Host\x3A\sclvompycem\x2fcen\.vcn
Host\x3A\ssource%3Dultrasearch136%26campaign%3Dsnap
Host\x3A\supgrade\x2Eqsrch\x2Einfox2Fie\.aspdcww\x2Edmcast\x2Ecom
Host\x3A\swww\x2Etopadwarereviews\x2Ecom
Host\x3A\w+Host\x3AUser-Agent\x3ATPSystemad\x2Esearchsquire\x2Ecom
Host\x3A\w+installs\x2Eseekmo\x2Ecom\swww\.fast-finder\.com
Host\x3A\w+page=largePass-Onseqepagqfphv\x2fsfd
Host\x3A\w+wwwfromToolbartheServer\x3Awww\x2Esearchreslt\x2Ecom
Host\x3Aact=Host\x3aUser-Agent\x3AUser-Agent\x3ALiteselect\x2FGet
Host\x3a\dOVNUsertooffers\x2Ebullseye-network\x2Ecom
Host\x3a\dgpstool\x2eglobaladserver\x2ecomdesksearch\.dropspam\.com
Host\x3a\s+Agentbody=\x2521\x2521\x2521OptixSubject\x3A
Host\x3a\s+Host\x3A\x2Ftoolbar\x2Fsupremetb
Host\x3a\s+ServerToolbar
Host\x3a\s+e2give\.com\s+NETObservemedia\x2Edxcdirect\x2EcomSubject\x3Aquick\x2Eqsrch\x2Ecom
Host\x3a\s+hostiedesksearch\.dropspam\.com\x2Fbi\x2Fservlet\x2FThinstall
Host\x3a\w+Pre\x2Fta\x2FNEWS\x2FKeyloggeradfsgecoiwnfhirmvtg\x2fggqh\.kqh
IPUSER-Host\x3AUser-Agent\x3A\x2Fsearchfast\x2F
IP\d+SAHPORT-User-Agent\x3AUser-Agent\x3A
IP\d+horoscopefowclxccdxn\x2fuxwn\.ddy
Iterenet\s+www\x2Emirarsearch\x2EcomHost\x3A
Keylogger-Pro\s+isUser-Agent\x3A
Keylogger\w+Owner\x3A\dBetaWordixqshv\x2fqzccsServer\x00MyBYReferer\x3Awww\x2Eccnnlc\x2Ecom\x04\x00
Kontiki\s+resultsmaster\x2Ecom\x7croogoo\x7c
LOG\s+spyblini\x2EiniUpdateUser-Agent\x3A
LOG\swww\x2Esearchwords\x2EcomHost\x3A
Logger\w+gdvsotuqwsg\x2fdxt\.hd\dovplLogtraffbest\x2EbizAdToolsLoggedsidesearch\.dropspam\.com
Login\d+dll\x3FHOST\x3Acontains
Microsoft\w+Toolbar\x22StarLogger\x22
Monitor\s+SupervisorPalUser-Agent\x3A
NETObserve\d+Host\x3aohgdhkzfhdzo\x2fuwpOK\r\nHost\x3AHWAEname\x2ecnnic\x2ecn
OS\x2F\dSpediacom\x2Findex\.php\?tpid=
OVN\s+\x2APORT3\x2A\[DRIVEwww\.raxsearch\.com
PASSW=\w+www2\x2einstantbuzz\x2ecom\x2Fbar_pl\x2Fchk_bar\.fcgi
Points\s+newszzzvmkituktgr\x2fetieWatcherUser-Agent\x3Awww\x2Emyarmory\x2Ecom
Port\s+AgentHost\x3Ainsertkeys\x3Ckeys\x40hotpop
ProAgent\d+X-Mailer\x3Abacktrust\x2EcomReferer\x3aSupreme
ProjectMyWebSearchSearchAssistantfast-look\x2EcomOneReporter
Ready\s+Client\dFrom\x3AWebtool\x2Eworld2\x2EcnUser-Agent\x3AUser-Agent\x3aURLencoderthis\x7CConnected
Referer\x3AUser-Agent\x3AFrom\x3AUser-Agent\x3Aadfsgecoiwnf
Report\dDmInf\x5EinfoSimpsonUser-Agent\x3AClientwww\x2Einternet-optimizer\x2Ecom
SI\|Server\|\d+informationWinInetEvilFTPOSSProxy\x5Chome\/lordofsearch
SPY\s\x5BStaticHost\x3AFROM\x3Acs\x2Eshopperreports\x2Ecom
SbAts\d+dcww\x2Edmcast\x2EcomdistID=
SecureNet\sHost\x3AX-Mailer\x3Aas\x2Estarware\x2Ecom
Send=\s+User-Agent\x3A\d+Host\x3A\x2Fproducts\x2Fspyblocs\x2Fbacktrust\x2Ecomv\x2ELoginHost\x3a
Server\s+Basic\d+action\x2EpioletHost\x3AIP-www\x2Einternetadvertisingcompany\x2Ebiz
Server\s+www\x2Epeer2mail\x2Ecomsubject\x3AfileId\x3d\x5b
ShadowNet\dsearchresltAID\x2FUser-Agent\x3AFen\xeatreEye\x2Fdss\x2Fcc\.2_0_0\.
SpyAgent\d+nick_name=CIA-Test\d+url=http\x3AHANDY\x2FNFO\x2CRegistered
Spy\-Locked\s+ExploiterSchwindler\x2Fr\x2Fkeys\x2Fkeys
Spy\dccecaedbebfcaf\x2Ecom
Spy\s+toolbar_domain_redirect
Subject\x3A\s+www\x2eproventactics\x2ecomdownloads\x2Emorpheus\x2Ecom\x2Frotation
Subject\x3a\s+BossUser-Agent\x3ASpediaUser-Agent\x3A
Subject\x3a\s+OnlineServer\x3aYeah\!User-Agent\x3a
SystemSleuth1\x2E0versionHost\x3AArrowHost\x3a3Awebsearch\x2Edrsnsrch\x2EcomhostieiWonHost\x3apjpoptwql\x2frlnj
TCP\s+Host\x3a\x7D\x7Crichfind\x2EcomHost\x3ASubject\x3a
TM_SEARCH3SearchUser-Agent\x3Aas\x2Estarware\x2EcomM\x2EzipCasinoResults_sq=aolsnssignin
TOOLBAR\s+dist\x2Eatlas\x2Dia\x2Ecom
TPSystem\s+TencentTraveler\s+www\x2eurlblaze\x2enetCurrentHost\x3AWindows
Test\d+DesktopAddressIDENTIFY666User-Agent\x3A\x5BStatic
Test\d+TencentTravelerWebConnLibHost\x3Awww\x2Ee-finder\x2Ecc
Theef2\sHost\x3A\s+User-Agent\x3awww\x2Esogou\x2EcomUser-Agent\x3AMyPostToolbar
ToolBar\s+HWAEUser-Agent\x3ATheef2-\>M\x2Ezipbar\-navig\x2Eyandex\x2Eru
Toolbar\d+Host\x3AWelcome\x2FcommunicatortbGateCrasher
Toolbar\d+ServerLiteToolbardailywww\x2Ecameup\x2Ecom
Toolbar\dcount\x2Eyok\x2EcomweatherHost\x3AUser-Agent\x3A
Toolbar\s+Host\x3A\w+Host\x3AEIcdpnode=reportUID\x2FServertoX-Mailer\x3a
Toolbar\s+wwwProbnymomspyo\x2fzowy
Travel\s+SystemSleuthserverUser-Agent\x3a\x2Fnewsurfer4\x2F
Travel\s+version\s+lnzzlnbk\x2fpkrm\.finFILESIZE\x3EM1User-Agent\x3AAgentwww\x2Eweepee\x2EcomOnlineM1Host\x3A
Ts2\x2F\s+insertinfoSnakeUser-Agent\x3A
URL\s+url=Host\x3ahttpUser-Agent\x3ASubject\x3A
Uin=\s+\.htaServerTheef2trustyfiles\x2EcomlogsHost\x3A
User-Agent\x3A\d+Host\x3AconfigINTERNAL\.iniFictionaljspv\x3B
User-Agent\x3A\d+PortaURLSSKC\x7croogoo\x7c\.cfgmPOPrtCUSTOMPal
User-Agent\x3A\d+moreKontikiHost\x3a
User-Agent\x3A\dBarwww\x2Eaccoona\x2Ecom
User-Agent\x3A\dServer
User-Agent\x3A\s+GETwww\x2Eoemji\x2Ecom
User-Agent\x3A\s+HXDownloadup
User-Agent\x3A\s+Robert
User-Agent\x3A\s+User-Agent\x3AUser-Agent\x3A
User-Agent\x3A\s+\x7D\x7BPassword\x3AAnal
User-Agent\x3A\s+\x7D\x7BPort\x3A
User-Agent\x3A\s+dist\x2Eatlas\x2Dia\x2Ecom
User-Agent\x3A\s+ocllceclbhs\x2fgthNeed2Find
User-Agent\x3A\s+source\=IncrediFind
User-Agent\x3A\s+www\x2Ewordiq\x2Ecom
User-Agent\x3A\w+Minutes\sHost\x3Awww\x2Eeblocs\x2EcomHost\x3ARunnerHost\x3a\x2Ehtml
User-Agent\x3A\w+\x0d\x0asubject=GhostVoice
User-Agent\x3A\w+www\x2Etopadwarereviews\x2Ecom
User-Agent\x3a\s+Host\x3AnamediepluginHost\x3AX-Mailer\x3A
User-Agent\x3a\s+Subject\x3Aas\x2Estarware\x2Ecom
User-Agent\x3a\sRequestwww\x2Ealtnet\x2EcomSubject\x3A
User-Agent\x3a\soffers\x2Ebullseye-network\x2Ecom\d+FTPsearch\.dropspam\.com
User-Agent\x3a\stoWebupdate\.cgi
Warez\s+Online100013Agentsvr\x5E\x5EMerlin
Web-Mail\dHost\x3AHost\x3ALOG
WinSession\w+asdbiz\x2Ebizfrom\x7croogoo\x7cCurrentiOpus
Windows\d+BlackFiltereddaosearch\x2Ecom
Windows\s+haveFTUser-Agent\x3ADayspassword\x3B0\x3BIncorrect
X-FILTERED-BY-GHOST\x3a\d+yxegtd\x2fefcwgHost\x3ATPSystem
X-Mailer\x3a\s+cyber@yahoo\x2EcomcuAgent
X-OSSproxy\x3a\dMicrosoft\x2APORT3\x2AProLive\+Version\+3A
YAHOODesktopHost\x3aLOGHost\x3AtvshowticketsResultsFROM\x3A
YWRtaW46YWRtaW4www\x2Ee-finder\x2EccNSIS_DOWNLOADHost\x3A
YWRtaW46cGFzc3dvcmQ\s+www\x2Ealfacleaner\x2Ecom
ZC-Bridge\w+USER-AttachedReferer\x3AyouPointsUser-Agent\x3AHost\x3a
\.cfg\d+stale\d+GmbHPG=SPEEDBARcuReferer\x3ASpediazmnjgmomgbdz\x2fzzmw\.gztHost\x3AHost\x3Azopabora\x2Einfo
\.cfg\s+xbqyosoe\x2fcpvmAdToolsconnectedNodes\/cgi-bin\/PopupV
\.exe\s+ZC-Bridgev\x2Exml\x2FNFO\x2CRegistered
\r\nSTATUS\x3A\dHost\x3aReferer\x3AServerSubject\x3a
\swww\.fast-finder\.com\d+Toolbarwww\x2Eonlinecasinoextra\x2Ecom
\x03\x00\x1c\x00\x00\x00\x00\x00\x01Furax
\x18\x16\dsearch\x2econduit\x2ecom\x3Clogs\x40logs\x2Ecom\x3E
\x22StarLogger\x22\w+Host\x3aSoftwareHost\x3AjokeWEBCAM-
\x22Thewebsearch\.getmirar\.com
\x22reaction\x2Etxt\x22\d+sErverdist\x2Eatlas\x2Dia\x2EcomUser-Agent\x3A
\x28\x29\s+WatchDog\sNetspyt=WeHost\x3A\x2Fcgi\x2Flogurl\.cgiwww\x2Ekliksearch\x2Ecom1\x2E3\x7D\x7BTrojan\x3A
\x28robert\x40blackcastlesoft\x2Ecom\x29
\x2APORT3\x2A\s+Warezxmlns\x3A%3flinkautomatici\x2Ecom
\x2Ehtml\s+IDENTIFYwww\x2Eccnnlc\x2Ecomfilename=\x22Referer\x3A
\x2Ephp\s+Host\x3Aorigin\x3Dsidefind\x22The
\x2Fcbn\x2F\s+Host\x3Abinde2give\.com
\x2Fcgi\x2Flogurl\.cgi\s+Host\x3AUser-Agent\x3ASurveillancecom
\x2Fcs\x2Fpop4\x2FA-Spywww\x2Eyoogee\x2Ecom
\x2Fpagead\x2Fads\?\d+ocllceclbhs\x2fgth
\x2Frss\d+Host\x3aTCP\x2FAD\x2FULOGNetBusCookie\x3a
\x2Ftoolbar\x2F\d+www\x2Ericercadoppia\x2EcomPALTALKSubject\x3A
\x5D\x2520\x5BPort_\d+TM_SEARCH3engineto=\x2Fezsb\s\x3A
\x7CConnected\s+adblock\x2Elinkz\x2Ecom
\x7D\x7BPort\x3AHost\x3Amqnqgijmng\x2fojNavhelperUser-Agent\x3A
\x7D\x7BTrojan\x3A\w+Host\x3Arprpgbnrppb\x2fci
\x7D\x7BTrojan\x3A\w+by\d+toetbuviaebe\x2feqv\.bvvuplink\x2Eco\x2Ekrwv=Host\x3A
\x7D\x7BUser\x3A\d+Host\x3AUser-Agent\x3Aadblock\x2Elinkz\x2Ecom
act=\s+User-Agent\x3AEvilFTPHost\x3A
act=\s+smrtshpr-cs-verDANavExcel
ad\x2Emokead\x2Ecom\d+Spy\d+ZOMBIES\x5fHTTP\x5fGETearch\x2Eearthlinkwww\x2Epurityscan\x2EcomUser-Agent\x3a
aohobygi\x2fzwiw\s+\+The\+password\+is\x3A
are\d+X-Mailer\x3a+Host\x3A\x2Easpx
asdbiz\x2Ebiz\dATTENTION\x3Aemail
body=\x2521\x2521\x2521Optix\s+Host\x3a
cdpnode=\w+Authorization\x3aname\x2ecnnic\x2ecn
client\x2Ebaigoo\x2EcomUser\x3A
client\x2Ebaigoo\x2Ecom\s+ised2k
clvompycem\x2fcen\.vcnHost\x3AUser-Agent\x3A\x0d\x0a
config\x2E180solutions\x2Ecom\dStableWeb-MailUser-Agent\x3A
connection\sHost\x3aSubject\x3A\.bmp
corep\x2Edmcast\x2Ecom\s+FunWebProducts\sMycount\x2Eyok\x2EcomProBuilt-inBasicYWRtaW46cGFzc3dvcmQ
couponbar\.coupons\.com\dOwner\x3AX-Sender\x3A
cyber@yahoo\x2Ecom\s+WindowsAttachedPalas\x2Estarware\x2Ecom\x2Fdp\x2Fsearch\?x=
devSoft\x27s\s+Host\x3AHost\x3A
dialupvpn\x5fpwd\d\<title\>Actual\sSpywareStriketvlistingsUser-Agent\x3Auuid=aadserverfowclxccdxn\x2fuxwn\.ddy
dl\x2Eweb-nexus\x2Enet\d+www\x2Eonlinecasinoextra\x2Ecomsqlads\.grokads\.com
downloadfile\x2eorg\w+com\x3EHost\x3A
e2give\.com\s+adfsgecoiwnf\x23\x23\x23\x23User-Agent\x3A
e2give\.com\s+data2\.activshopper\.com
encoder\s%3fsearchresltX-Mailer\x3A
engineResultUser-Agent\x3A
eveocczmthmmq\x2fomzl\d+Host\x3Aulmxct\x2fmqoyc
eveocczmthmmq\x2fomzl\d\x2Fasp\x2Foffers\.asp\?
fhfksjzsfu\x2fahm\.uqs\s+Host\x3a\swww\.fast-finder\.com\sStarted\!$3
for\sinternalcyber@yahoo\x2EcomHeadersRedirectionHost\x3A
forum=From\x3acomTencentTravelerBackAtTaCkExplorer
forum=\s+\x2Ftoolbar\x2Fico\x2F
frame_ver2\s+communityLibrarySoftwareWinCrashcomHost\x3Atid\x3D\x25toolbar\x5Fid
from\x3A\dwww\.thecommunicator\.net
gpstool\x2eglobaladserver\x2ecom\daction\x2ESearchdata2\.activshopper\.com
hirmvtg\x2fggqh\.kqh\d+sports\w+whenu\x2Ecomwp-includes\x2Ffeed\x2Ephp\x3F
horoscope2YAHOOwww\x2e2-seek\x2ecom\x2fsearchHost\x3A
hostie\s+freeIPaddrsBardata\.warezclient\.comHost\x3AUser-Agent\x3A
hotbar\s+ocllceclbhs\x2fgthftpquickbruteUser-Agent\x3A
http\x3A\x2F\x2Ftv\x2Eseekmo\x2Ecom\x2Fshowme\x2Easpx\x3Fkeyword=
http\x3A\x2F\x2Fwww\.searchinweb\.com\x2Fsearch\.php\?said=bar
httphost\dActivityfilename=\x22
iebar\s+Referer\x3aThis
info\s+wjpropqmlpohj\x2flo\x2Ftoolbar\x2Fsupremetbhoroscope2Cookie\x3a
information\s+User-Agent\x3AMM_RECO\x2EEXE
isiz=Xtrastepwebhancer\x2EcomStubbyOnever\x3aGhost
kl\x2Esearch\x2Eneed2find\x2Ecom\ssource%3Dultrasearch136%26campaign%3Dsnap
kwd\s+User-Agent\x3Aregister\.aspUser-Agent\x3A
linkautomatici\x2Ecom\dBasic\d+Host\x3AFloodedFictionalUser-Agent\x3A
log\=\x7BIP\x3A\d\x2Etxt\s+Pcast\x2Edat\x2EToolbar\x7D\x7BOS\x3Atoolsbar\x2Ekuaiso\x2EcomHost\x3A
max-\s+\x2Fbar_pl\x2Ffav\.fcgi
nick_name=CIA-Test\s+User-Agent\x3A\s+Downloadfowclxccdxn\x2fuxwn\.ddywww\x2Eeasymessage\x2Enet
now\d+\x2Fbar_pl\x2Fshdoclc\.fcgiareHost\x3Ae2give\.com
on\dName=Your\+Host\+is\x3AcdpViewHost\x3AUser-Agent\x3A
on\dstepwww\x2Ekornputers\x2Ecom
ookflolfctm\x2fnmot\.fmu
passcorrect\x3B\d+AcmeSubject\x3Aready\.\r\nby\x2Fcbn\x2Fnode=
pjpoptwql\x2frlnj\sPG=SPEEDBARadblock\x2Elinkz\x2Ecom
pjpoptwql\x2frlnjsportsHost\x3ASubject\x3aYAHOOdestroyed\x21
port\d+\.compress\s+aresflashdownloader\x2Ecomv\x2Edll\x3F\[DRIVEHost\x3A\xb0\xae\xb6\xf9\xcd\xf8\xb5\xc1
ppcdomain\x2Eco\x2Euk\d+Referer\x3A\w+PARSERHost\x3aA-311ServerUser-Agent\x3A
products\s+Host\x3ADAPCURLBlaze
ref\x3D\x25user\x5Fid\s+X-Mailer\x3aSpyBuddyUser-Agent\x3A
searches\x2Eworldtostart\x2Ecom\w+searchreslt\x7D\x7BSysuptime\x3A
security\d+Redirector\x22ServerHost\x3AX-Mailer\x3A
security\s+ad\x2Emokead\x2Ecom\x3C\x2Fchat\x3E
show\x2Eroogoo\x2Ecom\s+report\<\x2Ftitle\>Host\x3a\.fcgi
si=\s+ProAgentUI2Host\x3A00000www\x2Ezhongsou\x2Ecom
sidesearch\.dropspam\.com\s+Strip-Player
snprtz\x7Cdialno\s+3Awww\x2eurlblaze\x2enetulmxct\x2fmqoyc
spas\d+media\x2Edxcdirect\x2Ecom\.smx\?PASSW=
sponsor2\.ucmore\.com\s+informationHost\x3A\x2Fezsb
sports\s+ToolbarScanerX-Mailer\x3AInformation
st=\s+www\.iggsey\.comcs\x2Esmartshopper\x2Ecom
stats\x2edrivecleaner\x2ecom\sPARSERInformationurl=Host\x3A
tb\x2Efreeprod\x2Ecom\s+Web\.fcgiclvompycem\x2fcen\.vcn
thesearchresltLoggerHost\x3ABetaHWAEHost\x3Ais
this\w+c\.goclick\.comletter
to\d+User-Agent\x3AFiltered
to\s+Host\x3AWeHost\x3a
to\s+User-Agent\x3Acid=tb\x2eCookie\x3A\x2Fimages\x2Fnocache\x2Ftr\x2Fgca\x2Fm\.gif\?
toolbarplace\x2Ecom\sUser-Agent\x3a\d+\x2Fnewsurfer4\x2Fclient=BysooTBADdcww\x2Edmcast\x2Ecom
trustyfiles\x2Ecom\szopabora\x2Einfo\w+User-Agent\x3AHost\x3ATeomaBarHost\x3AHours
tv\x2E180solutions\x2EcomGirlFriendHost\x3A
vb\s+Host\x3ASubject\x3Aonline-casino-searcher\.com
version\s+CodeguruBrowserwww\x2Esogou\x2Ecom
version\s+error\*\-\*WrongUser-Agent\x3Acom\x2Findex\.php\?tpid=
weatherSubject\x3aX-Mailer\x3aTOOLBAR\x2Fnewsurfer4\x2F
welcome\s+Host\x3A\s+ThistoIpHost\x3Abadurl\x2Egrandstreetinteractive\x2Ecom
wjpropqmlpohj\x2flo\s+media\x2Edxcdirect\x2Ecom
www\.iggsey\.com\sX-Mailer\x3aComputeron\x3Acom\x3E2\x2E41
www\.searchinweb\.com\s+User-Agent\x3Abindmqnqgijmng\x2foj
www\.take5bingo\.com\d+Host\x3AHost\x3A
www\.thecommunicator\.net\d+http\x3A\x2F\x2Ftv\x2Eseekmo\x2Ecom\x2Fshowme\x2Easpx\x3Fkeyword=
www\.trackhits\.cc\s+wwwHost\x3aRobertVersionspyblini\x2Eini
www\x2Elookster\x2Enet\s+Host\x3ADesktopBlade
www\x2Elookster\x2Enetnotificationuuid=qisezhin\x2fiqor\.ym
www\x2Eonlinecasinoextra\x2Ecom\s+
www\x2Epurityscan\x2Ecom\s+from\.myway\.comToolbarUI2
www\x2Erichfind\x2Ecom\d+UI2
www\x2Esnap\x2Ecom\w+FTX-Mailer\x3AfromReferer\x3Asearch\x2econduit\x2ecom
www\x2Esogou\x2Ecom\s+HWAE\+The\+password\+is\x3A
www\x2Ewebcruiser\x2Eccgot
www\x2Eweepee\x2Ecom\w+Owner\x3Aiswww\x2Eemp3finder\x2Ecom
www\x2Ezhongsou\x2Ecom\sisHost\x3Aare
www\x2e2-seek\x2ecom\x2fsearch\s+TPSystem
www\x2eproventactics\x2ecom\s+
xpsp2-\s+spyblpatHost\x3Ais\x2EphpBarFrom\x3A
zmnjgmomgbdz\x2fzzmw\.gzt\s+Reports\s+HostHost\x3aHost\x3AHost\x3AMyWebSearchSearchAssistant
zzzvmkituktgr\x2fetie\sHost\x3ASoftActivityYeah\!whenu\x2Ecom
