
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package MonaParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUALS = 21;
  public static final int LPAREN = 14;
  public static final int GREATER = 23;
  public static final int WS1S = 6;
  public static final int LESS = 24;
  public static final int RPAREN = 15;
  public static final int IMPLICATION = 19;
  public static final int SEMICOLON = 10;
  public static final int AND = 18;
  public static final int IN = 28;
  public static final int OR = 17;
  public static final int COMMA = 36;
  public static final int M2LSTR = 8;
  public static final int PLUS = 35;
  public static final int LESSEQ = 25;
  public static final int ID = 4;
  public static final int VAR2 = 13;
  public static final int EOF = 0;
  public static final int VAR1 = 12;
  public static final int VAR0 = 11;
  public static final int EQUIVALENCE = 20;
  public static final int TRUE = 2;
  public static final int error = 1;
  public static final int NEGATION = 16;
  public static final int ALL2 = 33;
  public static final int ALL1 = 32;
  public static final int INTLITERAL = 5;
  public static final int COLON = 34;
  public static final int NOTIN = 29;
  public static final int NOTEQUALS = 22;
  public static final int EX2 = 31;
  public static final int EX1 = 30;
  public static final int GREATEREQ = 26;
  public static final int FALSE = 3;
  public static final int WS2S = 7;
  public static final int M2LTREE = 9;
  public static final int SUB = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TRUE",
  "FALSE",
  "ID",
  "INTLITERAL",
  "WS1S",
  "WS2S",
  "M2LSTR",
  "M2LTREE",
  "SEMICOLON",
  "VAR0",
  "VAR1",
  "VAR2",
  "LPAREN",
  "RPAREN",
  "NEGATION",
  "OR",
  "AND",
  "IMPLICATION",
  "EQUIVALENCE",
  "EQUALS",
  "NOTEQUALS",
  "GREATER",
  "LESS",
  "LESSEQ",
  "GREATEREQ",
  "SUB",
  "IN",
  "NOTIN",
  "EX1",
  "EX2",
  "ALL1",
  "ALL2",
  "COLON",
  "PLUS",
  "COMMA"
  };
}

