/* The following code was generated by JFlex 1.6.1 */

package MonaParser;

import java_cup.runtime.*;


class TokenVal {
  // fields
    int linenum;
    int charnum;
  // constructor
    TokenVal(int line, int ch) {
        linenum = line;
        charnum = ch;
    }
}

class IntTokenVal extends TokenVal {
  // new field: the value of the integer literal
    int intVal;
  // constructor
    IntTokenVal(int line, int ch, int val) {
        super(line, ch);
        intVal = val;
    }
}

class IdTokenVal extends TokenVal {
  // new field: the value of the identifier
    String idVal;
  // constructor
    IdTokenVal(int line, int ch, String val) {
        super(line, ch);
    idVal = val;
    }
}


// the current token starts on its line.
class CharNum {
    static int num=1;
}

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>mona.jlex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\31\1\47\1\47\1\32\22\0\1\3\5\0\1\37"+
    "\1\0\1\33\1\34\1\0\1\43\1\46\1\13\2\0\1\21\1\7"+
    "\1\10\7\1\1\44\1\45\1\42\1\36\1\41\2\0\32\2\4\0"+
    "\1\4\1\0\1\20\1\25\2\2\1\16\1\23\2\2\1\26\2\2"+
    "\1\12\1\11\1\27\1\30\2\2\1\15\1\6\1\14\1\22\1\17"+
    "\1\5\1\24\2\2\1\0\1\40\1\0\1\35\6\0\1\47\u1fa2\0"+
    "\1\47\1\47\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\12\3\2\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\10\3\1\22\1\3\1\23\1\24"+
    "\1\25\1\26\2\3\1\27\2\3\1\30\1\31\4\3"+
    "\1\32\1\33\1\34\1\0\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\2\3\2\0\1\43\1\44\2\0\1\45"+
    "\1\0\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[75];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\u0118"+
    "\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\50"+
    "\0\u0258\0\50\0\50\0\u0280\0\u02a8\0\50\0\50\0\u02d0"+
    "\0\u02f8\0\50\0\50\0\50\0\50\0\u0320\0\u0348\0\u0370"+
    "\0\u0398\0\u03c0\0\u03e8\0\u0410\0\u0438\0\170\0\u0460\0\50"+
    "\0\50\0\50\0\u0488\0\u04b0\0\u04d8\0\170\0\u0500\0\u0528"+
    "\0\170\0\170\0\u0550\0\u0578\0\u05a0\0\u05c8\0\50\0\170"+
    "\0\170\0\u05f0\0\170\0\170\0\170\0\170\0\170\0\170"+
    "\0\u0618\0\u0640\0\u0668\0\u0690\0\170\0\170\0\u06b8\0\u06e0"+
    "\0\50\0\u0708\0\50";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[75];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\1\7\2\3"+
    "\1\10\1\4\1\2\1\11\1\4\1\12\1\13\1\14"+
    "\1\3\1\4\1\15\2\4\1\16\1\17\1\4\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\52\0\1\3\5\0"+
    "\2\3\10\0\1\3\27\0\2\4\1\0\7\4\1\0"+
    "\15\4\22\0\1\5\45\0\2\4\1\0\2\4\1\36"+
    "\4\4\1\0\15\4\20\0\2\4\1\0\7\4\1\0"+
    "\6\4\1\37\6\4\20\0\2\4\1\0\4\4\1\40"+
    "\2\4\1\0\15\4\20\0\2\4\1\0\7\4\1\0"+
    "\1\4\1\41\13\4\20\0\2\4\1\0\7\4\1\0"+
    "\10\4\1\42\4\4\20\0\2\4\1\0\7\4\1\0"+
    "\4\4\1\43\10\4\20\0\2\4\1\0\6\4\1\44"+
    "\1\0\15\4\20\0\2\4\1\0\7\4\1\0\4\4"+
    "\1\45\10\4\20\0\2\4\1\0\7\4\1\0\13\4"+
    "\1\46\1\4\20\0\2\4\1\0\7\4\1\0\14\4"+
    "\1\47\50\0\1\20\54\0\1\50\52\0\1\51\44\0"+
    "\1\52\47\0\1\53\12\0\2\4\1\0\3\4\1\54"+
    "\1\55\2\4\1\0\15\4\20\0\2\4\1\0\7\4"+
    "\1\0\11\4\1\56\3\4\20\0\2\4\1\0\6\4"+
    "\1\57\1\0\15\4\20\0\2\4\1\0\7\4\1\0"+
    "\6\4\1\60\6\4\20\0\2\4\1\0\3\4\1\61"+
    "\1\62\2\4\1\0\15\4\20\0\2\4\1\0\7\4"+
    "\1\0\1\4\1\63\13\4\20\0\2\4\1\0\6\4"+
    "\1\64\1\0\15\4\20\0\2\4\1\0\6\4\1\65"+
    "\1\0\15\4\20\0\2\4\1\0\7\4\1\0\1\66"+
    "\14\4\60\0\1\67\7\0\2\4\1\0\2\4\1\70"+
    "\4\4\1\0\15\4\20\0\2\4\1\0\2\4\1\71"+
    "\4\4\1\0\15\4\20\0\2\4\1\0\7\4\1\72"+
    "\15\4\20\0\2\4\1\0\7\4\1\0\2\4\1\73"+
    "\12\4\20\0\2\4\1\0\3\4\1\74\1\75\2\4"+
    "\1\0\5\4\1\76\7\4\20\0\2\4\1\0\3\4"+
    "\1\77\1\100\2\4\1\0\15\4\20\0\2\4\1\0"+
    "\2\4\1\101\4\4\1\0\15\4\20\0\2\4\1\0"+
    "\7\4\1\0\12\4\1\102\2\4\25\0\1\103\5\0"+
    "\1\104\34\0\2\4\1\0\7\4\1\0\2\4\1\105"+
    "\12\4\20\0\2\4\1\0\7\4\1\0\13\4\1\106"+
    "\1\4\33\0\1\107\50\0\1\110\47\0\1\111\50\0"+
    "\1\112\47\0\1\113\31\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1840];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\15\1\1\11\1\1\2\11\2\1\2\11"+
    "\2\1\4\11\12\1\3\11\14\1\1\11\2\1\1\0"+
    "\10\1\2\0\2\1\2\0\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[75];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 158) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { return new Symbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { ErrMsg.fatal(yyline+1, CharNum.num,
                         "illegal character ignored: " + yytext());
            CharNum.num++;
            }
          case 39: break;
          case 2: 
            { double val = Double.parseDouble(yytext());
            int intVal;
            if (val > Integer.MAX_VALUE) {
                ErrMsg.warn(yyline+1, CharNum.num,
                            "integer literal too large; using max value");
                intVal = Integer.MAX_VALUE;
            } else {
                intVal = Integer.parseInt(yytext());
            }
            Symbol S = new Symbol(sym.INTLITERAL,
                             new IntTokenVal(yyline+1, CharNum.num, intVal));
            CharNum.num += yytext().length();
            return S;
            }
          case 40: break;
          case 3: 
            { Symbol S = new Symbol(sym.ID, 
                             new IdTokenVal(yyline+1, CharNum.num, yytext()));
            CharNum.num += yytext().length();
            return S;
            }
          case 41: break;
          case 4: 
            { CharNum.num += yytext().length();
            }
          case 42: break;
          case 5: 
            { CharNum.num = 1;
            }
          case 43: break;
          case 6: 
            { Symbol S = new Symbol(sym.LPAREN, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 44: break;
          case 7: 
            { Symbol S = new Symbol(sym.RPAREN, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 45: break;
          case 8: 
            { Symbol S = new Symbol(sym.NEGATION, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 46: break;
          case 9: 
            { Symbol S = new Symbol(sym.EQUALS, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 47: break;
          case 10: 
            { Symbol S = new Symbol(sym.AND, new TokenVal(yyline+1, CharNum.num));
            CharNum.num+=2;
            return S;
            }
          case 48: break;
          case 11: 
            { Symbol S = new Symbol(sym.OR, new TokenVal(yyline+1, CharNum.num));
            CharNum.num+=2;
            return S;
            }
          case 49: break;
          case 12: 
            { Symbol S = new Symbol(sym.GREATER, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 50: break;
          case 13: 
            { Symbol S = new Symbol(sym.LESS, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 51: break;
          case 14: 
            { Symbol S = new Symbol(sym.PLUS, new TokenVal(yyline+1, CharNum.num));
            CharNum.num+=2;
            return S;
            }
          case 52: break;
          case 15: 
            { Symbol S = new Symbol(sym.COLON, new TokenVal(yyline+1, CharNum.num));
            CharNum.num+=2;
            return S;
            }
          case 53: break;
          case 16: 
            { Symbol S = new Symbol(sym.SEMICOLON, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 54: break;
          case 17: 
            { Symbol S = new Symbol(sym.COMMA, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 55: break;
          case 18: 
            { Symbol S = new Symbol(sym.IN, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 56: break;
          case 19: 
            { Symbol S = new Symbol(sym.NOTEQUALS, new TokenVal(yyline+1, CharNum.num));
            CharNum.num++;
            return S;
            }
          case 57: break;
          case 20: 
            { Symbol S = new Symbol(sym.IMPLICATION, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 58: break;
          case 21: 
            { Symbol S = new Symbol(sym.GREATEREQ, new TokenVal(yyline+1, CharNum.num));
            CharNum.num += 2;
            return S;
            }
          case 59: break;
          case 22: 
            { Symbol S = new Symbol(sym.LESSEQ, new TokenVal(yyline+1, CharNum.num));
            CharNum.num += 2;
            return S;
            }
          case 60: break;
          case 23: 
            { Symbol S = new Symbol(sym.SUB, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 61: break;
          case 24: 
            { Symbol S = new Symbol(sym.EX1, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 62: break;
          case 25: 
            { Symbol S = new Symbol(sym.EX2, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 63: break;
          case 26: 
            { Symbol S = new Symbol(sym.EQUIVALENCE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 64: break;
          case 27: 
            { Symbol S = new Symbol(sym.WS1S, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 65: break;
          case 28: 
            { Symbol S = new Symbol(sym.WS2S, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 66: break;
          case 29: 
            { Symbol S = new Symbol(sym.TRUE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 67: break;
          case 30: 
            { Symbol S = new Symbol(sym.VAR1, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 68: break;
          case 31: 
            { Symbol S = new Symbol(sym.VAR2, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 69: break;
          case 32: 
            { Symbol S = new Symbol(sym.VAR0, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 70: break;
          case 33: 
            { Symbol S = new Symbol(sym.ALL1, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 71: break;
          case 34: 
            { Symbol S = new Symbol(sym.ALL2, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 72: break;
          case 35: 
            { Symbol S = new Symbol(sym.FALSE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 73: break;
          case 36: 
            { Symbol S = new Symbol(sym.NOTIN, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 74: break;
          case 37: 
            { Symbol S = new Symbol(sym.M2LSTR, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 75: break;
          case 38: 
            { Symbol S = new Symbol(sym.M2LTREE, new TokenVal(yyline+1, CharNum.num));
				CharNum.num +=yytext().length();
				return S;
            }
          case 76: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
