
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package TreeAutomataParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 2;
  public static final int COLON = 12;
  public static final int AUTOMATION = 4;
  public static final int TRANSITIONS = 7;
  public static final int EOF = 0;
  public static final int ARROW = 9;
  public static final int ID = 8;
  public static final int COMMA = 13;
  public static final int error = 1;
  public static final int RPAREN = 11;
  public static final int OPS = 3;
  public static final int FINALSTATES = 6;
  public static final int LPAREN = 10;
  public static final int STATES = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "OPS",
  "AUTOMATION",
  "STATES",
  "FINALSTATES",
  "TRANSITIONS",
  "ID",
  "ARROW",
  "LPAREN",
  "RPAREN",
  "COLON",
  "COMMA"
  };
}

